### ISSUE TITLE
Enable Semantics breaks typing into the search box

### ISSUE THREAD

**Issue by desmond206x** [widgetbook/widgetbook#1003]
**Description**
If flutter semantics are enabled, the search box of widgetbook does not work anymore. It is not possible to enter text.
![image](https://github.com/widgetbook/widgetbook/assets/833191/90168d6a-c0d7-49bd-b03a-8a9df16febed)

**Steps To Reproduce**
Add SemanticsBinding.instance.ensureSemantics(); to app to enable the semantics.

**Additional Context**
It seems that the error is in the flutter engine. So I hope you can contribute to this issue.
https://github.com/flutter/flutter/issues/129324

**Comment by adarsh-jha-dev** [comment]
Hey @desmond206x , could you please assign this issue to me?

**Comment by desmond206x** [comment]
I am not sure that I have the permissions to assign somebody.
I think @YoussefRaafatNasry can do it.

**Comment by YoussefRaafatNasry** [comment]
Hello @desmond206x 👋  
This issue is related to Flutter as you've mentioned.
I will be closing this for as it's not related to Widgetbook.
