### ISSUE TITLE
Dynamic List Knob

### ISSUE THREAD

**Issue by reyhanlioglu** [widgetbook/widgetbook#1013]
**Description**
It would be great if there is a knob that allows us provide runtime parameters. For example, lets say there is a BulletListWidget and it takes List<String>. Based on this list, it shows items line by line. By using dynamic list knob, we could observe how widget scales at runtime.

If you are familiar with Unity game engine, it is similar to use SerializedField on lists. You can add/remove game objects into serialized fields while playing the game.

Let me know if this feature request is not clear to understand.

**Comment by YoussefRaafatNasry** [comment]
Hello @reyhanlioglu 👋 
Can you provide more information to make the issue clear?
Preferably a code example as well.

**Comment by YoussefRaafatNasry** [comment]
I will close this for being stale for 2 weeks without any updates.
