### ISSUE TITLE
Addons not affecting new routes pushed by tested widgets

### ISSUE THREAD

**Issue by jtarkowski27** [widgetbook/widgetbook#1059]
**Description**

Addons exhibit flawed behavior when interacting with widgets that initiate their own route navigation via the app's navigator. It appears that the state managed by these addons primarily affects the main route within the Widgetbook's use case context, leading to inconsistencies when used with widgets navigating to new routes.

**Steps To Reproduce**

1. Add example use case with `DropdownButton`
2. Notice that changing text scale factor with `TextScaleAddon` doesn't increase text scale of list of options that opens after tapping the `DropdownButton`

Example use case code:

```dart
import 'package:flutter/material.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbook;

@widgetbook.UseCase(
  name: 'DropdownButton',
  type: DropdownButton,
)
Widget dropdownButtonUseCase(BuildContext context) {
  return Container(
    color: Colors.white,
    child: Center(
      child: DropdownButton(
        value: 'One',
        onChanged: (_) {},
        items: ['One', 'Two', 'Three', 'Four'].map((value) {
          return DropdownMenuItem(
            value: value,
            child: Text(value),
          );
        }).toList(),
      ),
    ),
  );
}
```

**Expected Behavior**

Ideally, addons should seamlessly integrate with widgets that perform route navigation, ensuring that these widgets behave correctly in different states and different accessibility settings.

As for `DropdownButton` case with `textScaleFactor=2.30` it should look like in the example below.

https://github.com/widgetbook/widgetbook/assets/45311300/a3d3f0c9-46f7-42a0-9e69-9b6a7360a5ce

**Actual behavior**

https://github.com/widgetbook/widgetbook/assets/45311300/09903944-f74b-48ab-91da-9fa6f8d49517

**Additional Context**

Widgetbook packages versions that I use.
```
widgetbook: 3.3.0
widgetbook_annotation: 3.0.0
widgetbook_generator: 3.2.0
```

**Comment by YoussefRaafatNasry** [comment]
Hello @jtarkowski27 👋 

I do not think this issue is related to Widgetbook.
Wrapping the `DropdownButton` with `MediaQuery` (which is used for `TextScaleAddon`) will still result in not affecting the 
`DropdownMenuItem`s as well. I would say this issue is more related to Flutter than to Widgetbook.

**Comment by YoussefRaafatNasry** [comment]
I will close this because of the reason mentioned above,
let us know if you have any further input, we can always re-open it if it's proven related to Widgetbook.
