### ISSUE TITLE
Missing SafeArea on bottom

### ISSUE THREAD

**Issue by Kiruel** [widgetbook/widgetbook#1060]
**Description**
Missing SafeArea when using on real device see screenshot.

**Steps To Reproduce**

1. Open the widgetbook on safari  
2. Add to home
3. Open from the home.

**Expected Behavior**
Should got a safearea on the bottom.

**Screenshots**
<img src="https://github.com/widgetbook/widgetbook/assets/8250175/fc44d34b-89c6-4ed8-ad75-9085939734b4" height=600px>

**Comment by YoussefRaafatNasry** [comment]
Hello @Kiruel 👋 
That's a good catch, I will push a fix, but no promises of having a release soon.

**Comment by YoussefRaafatNasry** [comment]
I have tried to fix that, but it seems like it's related to flutter and not to Widgetbook
See flutter/flutter#84833 for more info and possible solutions.
