### ISSUE TITLE
Get current value of knob with valueFromQueryGroup ?

### ISSUE THREAD

**Issue by gemunet** [widgetbook/widgetbook#1086]
**Description**
I am trying to get the current value of the knob using valueFromQueryGroup() but it always brings the default value. Is this how it is used?

**Steps To Reproduce**

WidgetbookState.of(context).knobs['mylabel']!.valueFromQueryGroup({})

**Comment by YoussefRaafatNasry** [comment]
To get the current value using `valueFromQueryGroup`, you need to do the following:

```dart
final state = WidgetbookState.of(context);
final groupMap = FieldCodec.decodeQueryGroup(state.queryParams['knobs']);
final knobValue = state.knobs['label']!.valueFromQueryGroup(groupMap);
```

Usually you do not need to retrieve knobs values like this, because you can reuse them as follows:

```dart
final isEnabled = context.knobs.boolean(...);

return MyCoolWidget(
  isEnabled: isEnabled,
  label: isEnabled ? 'Enabled' : 'Disabled'
);
```
