### ISSUE TITLE
Widgetbook cannot be run

### ISSUE THREAD

**Issue by LucasJosefiak** [widgetbook/widgetbook#113]
**Description**
After updating Widgetbook to 2.0.3.-beta, it's not possible to run Widgetbook anymore.

**Steps To Reproduce**

1. Update Widgetbook to 2.0.3.-beta
2. Run Widgetbook
3. See error

**Expected Behavior**
Widgetbook should run.

**Screenshots**
<img width="1149" alt="Screenshot 2022-02-06 at 12 35 25" src="https://user-images.githubusercontent.com/69841305/152679023-3c041fc0-eeca-4aa6-98c9-0909dcab531e.png">

**Comment by JensHor** [comment]
This compiles on flutter 2.10. As stated in the error message, the implementation uses a renamed property which is not available in flutter versions <= 2.8. I'll investigate which flutter versions will be supported in the future and document the decision.

**Comment by JensHor** [comment]
as of the flutter docs `primaryVariant` and `secondaryVariant` is deprecated as of flutter 2.6. Therefore, we'll support the latest version of flutter.
