### ISSUE TITLE
Widgetbook window on MacOS opens with very small window

### ISSUE THREAD

**Issue by Adam-Langley** [widgetbook/widgetbook#1139]
**Description**
On cold start on MacOS, the main window opens so small (~2x50 pixels) that I often cannot even find it.

**Steps To Reproduce**

1. clean compile and cold start

**Expected Behavior**
Window should open at a reasonable size - i.e 200x200px?

**Screenshots**
<img width="332" alt="image" src="https://github.com/widgetbook/widgetbook/assets/16373742/a2370daf-7cf7-4d84-a279-30fb5d8abaaf">

**Comment by YoussefRaafatNasry** [comment]
Hello @Adam-Langley 👋 
This issue doesn't seem related to Widgetbook, it might be a misconfiguration in the flutter app wrapping Widgetbook./
Closing this as it is not reproducible.
