### ISSUE TITLE
docs: "Missing" --branch Argument in Cloud PR Setup

### ISSUE THREAD

**Issue by ABausG** [widgetbook/widgetbook#1142]
https://github.com/widgetbook/widgetbook/blob/0d30bc586456cad337d3ccaf2f6c8c4a8e3611c0/docs/widgetbook-cloud/setup.mdx#L115

Just copying over the snippet for uploading works fine, however all uploads are then showing in Widgetbook Cloud as coming from `HEAD`. Maybe adding either a snippet of documentation and/or extending the example code snippet to show the addition of `--branch` might be helpful.

I guess having something generic like

```bash
widgetbook publish --api-key API-KEY --base-branch main --branch your-branch
```

would keep the same syntax abstraction of users having to swap to their CI/CD system like with the API-KEY.

**Comment by YoussefRaafatNasry** [comment]
The branch should have a fallback value to the current branch, if that's not working properly for you, please provide us with more information to help you further.

https://github.com/widgetbook/widgetbook/blob/0d30bc586456cad337d3ccaf2f6c8c4a8e3611c0/packages/widgetbook_cli/lib/src/commands/publish.dart#L88

**Comment by YoussefRaafatNasry** [comment]
Closing this as it is non-reproducible.
