### ISSUE TITLE
IsInitallyExpanded for Addons

### ISSUE THREAD

**Issue by SlowDeepCoder** [widgetbook/widgetbook#1172]
Addons are super useful, however 90% of the times we don't really use them. So they end up being mostly in the way and being a strain to the eyes when trying to find the correct knobs. And we find ourselves restricitng how many addons we are using since if it's too many of them, we have to unexpand the addon list manually each time before we can continue testing with the knobs.

Having a property `isAddonsInitallyExpanded` for the Widgetbook would be amazing to solve this issue. 

Here is an example of one of our simplest component, it has only one knob to select the color and the addons doesn't really provide anything useful for this component:
<img width="771" alt="addonsScrolledUp" src="https://github.com/widgetbook/widgetbook/assets/29180990/f5089595-e83b-412e-adce-2bd7f3f85b6a">

<img width="771" alt="addonsScrolledDown" src="https://github.com/widgetbook/widgetbook/assets/29180990/417ece43-187b-4d99-b2e9-51df40131a00">

**Comment by YoussefRaafatNasry** [comment]
A similar change was proposed in #706, but we decided not to proceed with it back then.
We will be re-evaluating this option and the one you've suggested.

**Comment by SlowDeepCoder** [comment]
> A similar change was proposed in #706 _(without Knobs as default tab)_, but we decided not to proceed with it back then. We will be re-evaluating this option and the one you've suggested.

That's a great suggestion! I showed it to my collegaues as well and they all like the tabs, as long as is it would be possible to have the knobs as the default tab :)
