### ISSUE TITLE
Inspector Addon Is Not Working on the Demo

### ISSUE THREAD

**Issue by aaulia** [widgetbook/widgetbook#1180]
**Description**
Inspector Addon doesn't work on Widgetbook Demo

**Steps To Reproduce**

1. Go to https://demo.widgetbook.io
2. Enable Inspector
3. Set Device and Frame, to None
4. Click on one of the entry on the left
5. Inspector didn't show in the right side of the content section

**Expected Behavior**
Inspector shows up

**Screenshots**
![Screenshot from 2024-05-31 06-56-40](https://github.com/widgetbook/widgetbook/assets/161797/619ada03-354d-4ada-8932-53d2e2cd924a)

**Additional Context**
I want to integrate inspector add-on to my own project. So I want to test it out first.

**Comment by YoussefRaafatNasry** [comment]
Hello @aaulia 👋 

Thank for reporting this! I can confirm that the Inspector Addon is no longer working on our demo. We will look into it soon again and let you know.

This could be related to the latest Flutter release, because we fixed a similar issue in #1085 before.
