### ISSUE TITLE
MediaQuery based on Widgetbook window instead of simulated screen

### ISSUE THREAD

**Issue by siliconivan** [widgetbook/widgetbook#119]
**Description**
The use of MediaQuery seems to be based on the Widgetbook window rather than the the simulated screen. (Video attached)

**Steps To Reproduce**

1. Run the following code as your Widgetbook and you will see that the blue Container moves to the left when you scale the Widgetbook window.

```
return Widgetbook(
      themes: [WidgetbookTheme(name: "Light", data: ThemeData.light())],
      categories: [
        WidgetbookCategory(
          name: 'widgets',
          widgets: [
            WidgetbookWidget(
              name: 'some widget',
              useCases: [
                WidgetbookUseCase(
                  name: 'Default',
                  builder: (context) => Container(
                    color: Colors.green,
                    width: MediaQuery.of(context).size.width,
                    height: MediaQuery.of(context).size.height,
                    child: Padding(
                      padding: EdgeInsets.only(
                        left: MediaQuery.of(context).size.width * 0.25,
                      ),
                      child: Container(
                        color: Colors.blue,
                        width: 250,
                        height: 250,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ],
      appInfo: AppInfo(
        name: 'Widgetbook Example',
      ),
    );
```

**Expected Behavior**
Expect MediaQuery to be based on the simulated screen rather than the window of Widgetbook.

**Screenshots**

https://user-images.githubusercontent.com/13757212/152865736-df523918-c067-4c03-94e8-265404132eb3.mov

**Additional Context**
The issue comes up on both Widgetbook 1.0.3 & 2.0.3-beta
flutter version: 2.10.0
dart version: 2.16.0

**Comment by JensHor** [comment]
Hey @siliconivan, thanks for creating an issue 👍🏻 We are aware of the issue and tracking this in issue https://github.com/widgetbook/widgetbook/issues/66 as well. The issue is on our timeline this week and will likely land on Thursday or Friday for version 2.0.x

**Comment by JensHor** [comment]
Re-opened since the problem was raised via discord feedback.

**Comment by smsimone** [comment]
Is there any update on this issue?
