### ISSUE TITLE
Adding low-code features

### ISSUE THREAD

**Issue by Ingenu1ty** [widgetbook/widgetbook#1212]
hi all👋 Developing widgets in isolation is a very useful thing! But it would be even better if this were combined with a **low-code approach** to create business logic🚀 

As a low-code tool I suggest considering [Lowder](https://github.com/HCaseira/lowder_flutter). I mean something like seamless integration(with Knobs to props, etc...) of widgets from the Widgetbook library into the Lowder...

**Comment by Ingenu1ty** [comment]
> Do you think it can be integrated in widgetbook 3?

It looks more like the widgetbook can be integrated into Lowder :) Or at least Widgetbook could have the ability to be **interoperable** with lowder. Lowder is quite an interesting low-code solution, but it **lacks cataloging and management capabilities("Use-cases", "Variants" and other useful things)** for widgets... 

Actually, I posted this here because it looks like your project has a solid team that is capable of developing tools that simplify the development of flutter apps... Perhaps you might even want to fork lowder, combining widgetbook and lowder into one cool project :-)

**Comment by LucasJosefiak** [comment]
While we'd love to work on that too, we however need to focus the resources of our team on enabling Flutter developers to catalog their widgets in a design system. As we unfortunately won't be able to work on this anytime soon, I'm closing this issue. 

If anyone wants to contribute to this issue, please feel free to re-open it.
