### ISSUE TITLE
Flutter 3.24 error

### ISSUE THREAD

**Issue by frederikstonge** [widgetbook/widgetbook#1220]
**Description**
![image](https://github.com/user-attachments/assets/300f3d25-495f-4e30-87ee-d4134a7706f9)

![image](https://github.com/user-attachments/assets/197c14c9-8895-4718-b937-24582b388af3)

**Steps To Reproduce**

Update flutter to 3.24

**Expected Behavior**
Widgetbook should appear

**Comment by YoussefRaafatNasry** [comment]
Hello @frederikstonge 👋 
I was not able to reproduce it on the stable channel. Did you run `flutter packages upgrade` after upgrading to v3.24?

**Comment by frederikstonge** [comment]
> Hello @frederikstonge 👋 I was not able to reproduce it on the stable channel. Did you run `flutter packages upgrade` after upgrading to v3.24?

Yes, and after setting the channel back to stable, i'm getting the same issue.

**Comment by frederikstonge** [comment]
forgot to mention, it's on web platform

**Comment by rafaelcmm** [comment]
+1

**Comment by yousinix** [comment]
I will close this issue as it is not reproducible from our end.
If you have minimal reproduction example that can help us with further investigation, I will be happy to re-open/help.
