### ISSUE TITLE
Text scale widget should be a slider

### ISSUE THREAD

**Issue by ash14** [widgetbook/widgetbook#1223]
A slider widget seems more suitable for this addon control than a dropdown IMO. Was there any reason this wasn't originally done?

Implementing this is rather straightforward and is only a minor update from the existing `TextScaleAddon`:

```dart
class TextScaleSliderAddon extends WidgetbookAddon<double> {
  TextScaleSliderAddon({
    this.min = 0.8,
    this.max = 2.0,
    this.divisions = 6,
    this.initialScale = 1.0,
  }) : super(
          name: 'Text scale',
        );

  final double min;
  final double max;
  final int divisions;
  final double initialScale;

  @override
  List<Field> get fields {
    return [
      DoubleSliderField(
        name: 'factor',
        initialValue: initialScale,
        min: min,
        max: max,
        divisions: divisions,
      ),
    ];
  }

  @override
  double valueFromQueryGroup(Map<String, String> group) {
    return valueOf('factor', group)!;
  }

  @override
  Widget buildUseCase(
    BuildContext context,
    Widget child,
    double setting,
  ) {
    return MediaQuery(
      data: MediaQuery.of(context).copyWith(
        textScaler: TextScaler.linear(setting),
      ),
      child: child,
    );
  }
}
```

See demo below:

https://github.com/user-attachments/assets/5c4e68af-3593-4630-a516-f8e3328bb499

**Comment by YoussefRaafatNasry** [comment]
Hello @ash14 👋 

Great suggestion! We even considered it for Widgetbook v4 [here](https://github.com/widgetbook/widgetbook/blob/v4/packages/widgetbook/lib/src/addons/text_scale_addon.dart). But I see how this can also improve the UX for v3. Would you like to submit a PR with that change?

**Comment by ash14** [comment]
Thanks for the quick response! PR raised.
