### ISSUE TITLE
Option to force dark mode for Widgetbook

### ISSUE THREAD

**Issue by MarkOSullivan94** [widgetbook/widgetbook#1228]
**Description**

I would love to have Widgetbook use dark mode instead of Widgetbook using my system settings on my Macbook. It feels weird to have to change my MacOS theme to be able to use dark mode.  

**Expected Behavior**

To have an optional parameter when creating the Widgetbook widget

```dart
return Widgetbook.material(
    directories: directories,
    themeMode: ThemeMode.dark,
);
```

**Comment by YoussefRaafatNasry** [comment]
Hello @Mastersam07 👋 
Yeah, let's add it there.

_(BTW, great work with the PRs, I will review them tomorrow)_

**Comment by MarkOSullivan94** [comment]
Thanks @Mastersam07 for adding this
