### ISSUE TITLE
listOrNull knob shouldn't be enabled by default

### ISSUE THREAD

**Issue by hectorAguero** [widgetbook/widgetbook#1231]
**Description**
I want to show the null value by default when a user see the widget on widgetbook, but the listOrNull knob has the options.first as default value so it's impossible in a easy way

**Steps To Reproduce**

1. Go to lib/src/knobs/builders/knobs_builder.dart

**Expected Behavior**
listOrNull should'nt have a defaultValue.

```dart
  T? listOrNull<T>({
    required String label,
    required List<T?> options,
    T? initialOption,
    String? description,
    LabelBuilder<T?>? labelBuilder,
  }) {
    assert(options.isNotEmpty, 'Must specify at least one option');
    return onKnobAdded(
      ListKnob<T?>.nullable(
        label: label,
        initialValue: initialOption ?? options.first, // Remove options.first
        description: description,
        options: options,
        labelBuilder: labelBuilder,
      ),
    );
  }
````

**Comment by yousinix** [comment]
Hello @hectorAguero! 👋

Thanks for reporting this issue. 
It makes sense to remove `options.first`. I've submitted a PR to fix this, and it will be available in our next release.
