### ISSUE TITLE
Dragging causes the story function to re-run every time

### ISSUE THREAD

**Issue by eertmanhidde** [widgetbook/widgetbook#124]
**Description**
It seems to me that dragging re-runs the story function every time, we're using Faker to generate some lorem ipsum. The following function is being re-run every drag: `faker.lorem.sentences(8).join(' ')`

**Steps To Reproduce**

1. Create a Story
2. Include some function in that story (a print for example)
3. Drag inside the story
4. Notice your function being called every drag

**Expected Behavior**
I personally wouldn't expect the function to re-run every drag. Only once during initiation.

**Screenshots**
(no screenshot but a video)
https://user-images.githubusercontent.com/45388384/153224805-11b1837c-7919-4cdf-84fc-b4d8885b74da.mp4

**Additional Context**
The code for my story
```dart
var faker = Faker();

@WidgetbookUseCase(name: 'Default', type: Section)
Widget defaultSectionStory(BuildContext context) {
  return WidgetbookWrapper(
    child: Scaffold(
      body: Section(
        child: Text(faker.lorem.sentences(8).join(' ')),
      ),
    ),
  );
}
```
Perhaps the way I'm generating the data is incorrect? 🤷🏻‍♂️

**Comment by JensHor** [comment]
The way you are generating the data seems to be fine. This is likely caused by the implementation of widgetbook. Which version (1.0.x or 2.0.x) are you using?
