### ISSUE TITLE
AlertDialog.adaptive Displays iOS Theme When Wrapped with Android Device Frame

### ISSUE THREAD

**Issue by Shahad-999** [widgetbook/widgetbook#1246]
**Description**
When wrapping a widget with an Android device frame in the Widgetbook package, the AlertDialog.adaptive widget displays with an iOS-style theme instead of the expected Android theme. This creates a visual inconsistency, as the dialog does not align with the native design conventions of the Android platform. 

**Steps To Reproduce**

1. Add a button to show `AlertDialog.adaptive`
2. Run the application and use the Android device frame  
3. Click on the show dialog button
4. The dialog appears with the iOS theme on an Android device frame.
![image](https://github.com/user-attachments/assets/9068f6fb-ca32-4a69-bf0b-72d808df9c41)

**Expected Behavior**
When running the app on an Android device the dialogue 
<img width="364" alt="Screenshot 2024-08-22 at 11 14 32 AM" src="https://github.com/user-attachments/assets/44e12e01-46bf-404e-a22c-4bddb6eaa3f6">

**Comment by yousinix** [comment]
Hello @Shahad-999 👋 
Thanks for reporting this isssue!

Please provide us with a reproduction repo, to make it easier for us to reproduce this.

**Comment by yousinix** [comment]
I will be closing this issue for being stale for long.
I will re-open once we have a reproduction code for it.
