### ISSUE TITLE
[improve docs] better snippet for adding stry

### ISSUE THREAD

**Issue by satvikreddy** [widgetbook/widgetbook#1283]
**Description**
Suggestion to improve vscode snippet in [next/sam docs](https://docs.widgetbook.io/next/sam#visual-studio-code)

For most people i think this version of snippet works better.
1. Widget name is derived from filename: super_cool_widget.stories.dart => SuperCoolWidget
2. both variable name and the parameter name are in snippet argument.

```
  "Widgetbook Story": {
    "prefix": "stry",
    "description": "Creates a new Widgetbook Story",
    "body": [
      "import 'package:flutter/widgets.dart';",
      "import 'package:widgetbook/next.dart';",
      "",
      "part '$TM_FILENAME_BASE.book.dart';",
      "",
      "",
      "final meta = Meta<${TM_FILENAME_BASE/(^[^.]+)(.*)/${1:/pascalcase}/}>();",
      "",
      "final $${1:storyname} = ${TM_FILENAME_BASE/(^[^.]+)(.*)/${1:/pascalcase}/}Story(",
      "  name: '${1:storyname}',",
      ");"
    ]
  }
```

https://github.com/user-attachments/assets/3e38b88b-8fd9-4026-9e43-0f7b1505f793

**Comment by yousinix** [comment]
Hello @satvikreddy 👋 

That would be a nice improvement.
We can also make the story name's placeholder "Default" so that users do not need to type anything in most cases.

To have such a snippet for VS Code, it would be great if we have a similar one for JetBrains IDE as well, and you can submit a PR with both.

**Comment by satvikreddy** [comment]
@yousinix PR https://github.com/widgetbook/widgetbook/pull/1285
I do not have/use jetbrains. It does not seem to offer any inbuilt template pascal case transformations.
