### ISSUE TITLE
animation does not work with Stateless Widgets

### ISSUE THREAD

**Issue by kyle-xje** [widgetbook/widgetbook#1303]
**Description**
For Stateless Widgets, if the animation is controlled by a flag that is a param, the animation does not work.
If the animation is controlled by a state within a Stateful Widget, it works.

**Steps To Reproduce**
Code example below:

```
class Switch extends StatelessWidget {
  final bool isChecked;
  final Function()? onTap; // should be a function passed from the parent to update the isChecked

  const Switch({super.key, required this.isChecked, this.onTap});

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
        onTap: onTap,
        child: Container(
          width: 40,
          height: 24,
          decoration: BoxDecoration(
            color: isChecked ? Colors.blue : Colors.grey,
            borderRadius: const BorderRadius.all(Radius.circular(16)),
          ),
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 3),
            child: AnimatedAlign(
              alignment: isChecked ? Alignment.centerRight : Alignment.centerLeft,
              duration: const Duration(milliseconds: 150),
              child: Container(
                width: 18,
                height: 18,
                decoration: const BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.all(Radius.circular(16)),
                ),
              ),
            ),
          ),
        ),
    );
  }
}

@widgetbook.UseCase(
  name: 'Default',
  type: Switch,
)
Widget defaultSwitch(BuildContext context) {
  return Switch(
    isChecked: context.knobs.boolean(label: 'is checked'),
  );
}
```

**Expected Behavior**
The Widget should animate when we click on the knob for `isActive`

**Screenshots**

**Additional Context**
If the widget is a Stateful widget, more specifically, the `isChecked` is a state, and `onTap` is a function that toggles `isChecked`, then the animation works. Example code: https://api.flutter.dev/flutter/widgets/AnimatedAlign-class.html

The theory I have is, when the knob is toggled, widgetbook renders a completely new widget instead of keeping the widget and renders a new state. The does not represent how a Widget works inside an application, and we lose the ability to preview the animation of Stateless Widgets in Widgetbook.

**Comment by yousinix** [comment]
Thanks for reporting this, @kyle-xje!

This is a challenging problem to fix ourselves, as some users prefer resting their widget after a knob change, and other do not. So we [have decided to make resetting everything the default behavior](https://github.com/widgetbook/widgetbook/issues/788#issuecomment-1801828212).

You can still opt-out of that by using a `GlobalKey` as follows.

```dart
final _key = GlobalKey();

@widgetbook.UseCase(
  name: 'Default',
  type: Switch,
)
Widget defaultSwitch(BuildContext context) {
  return Switch(
    key: _key,
    isChecked: context.knobs.boolean(label: 'is checked'),
  );
}
```

**Comment by kyle-xje** [comment]
thank you!
