### ISSUE TITLE
Unable to use device frame addon with windows and linux laptops

### ISSUE THREAD

**Issue by Isakdl** [widgetbook/widgetbook#1314]
**Description**
If I add both a windows laptop and a linux laptop I cannot switch between them.

It seems like the selection in the device frame list is based on the title of the button rather than the index, as it always selects the first entry called "Laptop".

Functionally not a huge issue as both devices looks like they are the same but with a slightly different background.

**Steps To Reproduce**
Add the `DeviceFrameAddon` like so:

```dart
DeviceFrameAddon(
 devices: [
    Devices.windows.laptop,
    Devices.linux.laptop,
  ],
),
```

**Expected Behavior**
I should be able to switch between the windows and linux laptop.

**Screenshots**

Video of issue:
https://github.com/user-attachments/assets/8955af93-b786-4111-a513-2bb1c773de0a

**Comment by Isakdl** [comment]
Additional note: This problem is a little worse than I initially thought as it also affects any devices that happen to have the same name. E.g. `Devices.android.largeTablet` and `Devices.macOS.wideMonitor` are both called `Large`.

It would be nice with a slightly more descriptive title here too.

**Comment by yousinix** [comment]
Hello @Isakdl 👋
Thanks for reporting this!

As we are using [`device_frame`](https://pub.dev/packages/device_frame) package for previewing on multiple devices, we do not have much control over the exported `Devices` list.

A quick workaround would be to create a copy of those devices with a unique name as follows:

```dart
DeviceFrameAddon(
 devices: [
   Devices.windows.laptop.copyWith(
     name: 'Windows Laptop',
    ),
    Devices.linux.laptop.copyWith(
      name: 'Linux Laptop',
    ),
  ],
),
```

On the other hand, we are planning to create our own zero-dependency `DeviceAddon` in the upcoming weeks. That will result in deprecating `DeviceFrameAddon`. So I will be closing this issue as we won't be supporting that addon any longer.
