### ISSUE TITLE
Widgetbook cloud, Integration support for self-hosted GitLab and CLI-based build review capabilities.

### ISSUE THREAD

**Issue by treestae** [widgetbook/widgetbook#1316]
Is it not possible to integrate with self-hosted GitLab installed on company servers?
Or is there no way to review builds that were pushed using just the CLI?

**Comment by yousinix** [comment]
Hello @treestae 👋 

We have added support to self-hosted GitLab a couple of weeks ago.
You can check out [this document](https://docs.google.com/document/d/1lvfBHRazqz3M0wBP9H_mphCO0Ka4vj0eT3VpUw5bUoQ/edit?usp=sharing) for more information.
This section will be avilable in our docs soon as well.
