### ISSUE TITLE
Mock WidgetbookState or KnobsBuilder in unit tests.

### ISSUE THREAD

**Issue by haodong404** [widgetbook/widgetbook#1319]
**Description**
I'm trying to write golden tests with Widgetbook like below:
```dart
@UseCase(name: 'ExampleText', type: Text, path: 'widgets')
Widget exampleTextUseCase(BuildContext context) {
  return Center(child: Text(context.knobs.string(label: 'title', initialValue: 'Default Value')));
}
```

Because I'm using `context.knob` to modify the parameters, so I can not use `tester.pumpWidget(Builder(builder: exampleTextUseCase))` to pump a widget. 
```
The following _TypeError was thrown building Builder:
Null check operator used on a null value

...

When the exception was thrown, this was the stack:
#0      WidgetbookState.of (package:widgetbook/src/state/widgetbook_state.dart:79:63)
#1      KnobsExtension.knobs (package:widgetbook/src/knobs/builders/knobs_extension.dart:11:35)
...
```

So is there a way to mock knob or WidgetbookState in unit test?

**Comment by yousinix** [comment]
Hello @haodong404 👋 

You need to wrap your use-cases in a `WidgetbookScope` to make this work.
You can find an example here: https://github.com/widgetbook/widgetbook/blob/02cdb368afea4d45aca7b8f2c72755285e0665a6/packages/widgetbook/test/helper/tester_extension.dart#L50-L64

By the way, if you are try to write golden tests, you might need to check out [Widgetbook Cloud](https://docs.widgetbook.io/cloud), which is a zero-configuration golden testing solution, that comes with other benefits like reviews, CI/CD integration, etc.

**Comment by Windisch94** [comment]
hi @yousinix 
I also have the same problem but the WidgetbookScope class is internal only, so I cant use that

**Comment by yousinix** [comment]
I have submitted a PR to improve the imports.
To my knowledge, the following import won't cause linter error in `test/`, only in `lib/`. 

```dart
import 'package:widgetbook/src/state/widgetbook_scope.dart';
```

So you can use it until the improvment in #1325 gets released, which will change the import to be:

```dart
import 'package:widgetbook/widgetbook.dart';
```
