### ISSUE TITLE
Position of DropdownMenu is displaced

### ISSUE THREAD

**Issue by ilia-korolev** [widgetbook/widgetbook#1334]
**Description**
Since Flutter 3.27, the position of the DropdownMenu is displaced in Widgetbook.

**Steps To Reproduce**

1. Create Widgetbook with the following:
```dart
import 'package:flutter/material.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbook;

void main() {
  runApp(const WidgetbookApp());
}

@widgetbook.App()
class WidgetbookApp extends StatelessWidget {
  const WidgetbookApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
      directories: [
        WidgetbookUseCase.child(
          name: 'Dropdown',
          child: Scaffold(
            body: Center(
              child: DropdownMenu(
                dropdownMenuEntries: [
                  DropdownMenuEntry(value: 1, label: 'One'),
                  DropdownMenuEntry(value: 2, label: 'Two'),
                  DropdownMenuEntry(value: 3, label: 'Three'),
                ],
              ),
            ),
          ),
        ),
      ],
    );
  }
}
```
2. Select "Dropdown" use case
3. Tap on the DropdownMenu widget

**Expected Behavior**
The DropdownMenu appears below the anchor.

**Screenshots**
<details>
  <summary>Screenshots</summary>
  <img width="600" alt="image" src="https://github.com/user-attachments/assets/df3acf66-e239-429b-836b-465c3febad3e" />
  <img width="600" alt="image" src="https://github.com/user-attachments/assets/cf8e8d7d-1c6a-4539-a898-9d3b5364403d" />
</details>

**Additional Context**
Widgetbook version: 3.10.1

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.2 24C101 darwin-arm64, locale en-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.96.0)
[✓] Connected device (5 available)
[✓] Network resources

**Comment by yousinix** [comment]
Hello @ilia-korolev 👋 

Seems like this is a regression with Flutter itself.
The following non-Widgetbook code behaves differently on Flutter versions 3.27 and 3.16

```
import 'package:flutter/material.dart';

void main() {
  runApp(const HostApp());
}

class HostApp extends StatelessWidget {
  const HostApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Padding(
          padding: EdgeInsets.all(100),
          child: InsideApp(),
        ),
      ),
    );
  }
}

class InsideApp extends StatelessWidget {
  const InsideApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: const Center(
        child: DropdownMenu(
          dropdownMenuEntries: [
            DropdownMenuEntry(
              value: 1,
              label: 'Option 1',
            ),
          ],
        ),
      ),
    );
  }
}
```

I will close this as we cannot help much with it.
