### ISSUE TITLE
Feature Request: Custom positioning of Viewport Controls

### ISSUE THREAD

**Issue by m4w** [widgetbook/widgetbook#137]
**Description**
I like to suggest a little feature, which would help us a lot, viewing widgetbook on smaller screens. Often the viewport controls are blocking content in our widget. I added an image of the controls I meant.

**Expected Behavior**
It would be great, if thoses controls could be moved either on the fly or via config. Also it would be great to toggle visibility (maybe with a button in the upper toolbar).

**Screenshots**
![image](https://user-images.githubusercontent.com/1598385/157302617-e20c264d-a481-46d9-bfbc-de49924528a0.png)

**Comment by JensHor** [comment]
Hi @m4w, thanks for opening an issue - we always appreciate the feedback 👍🏻 We are aware that the UX of `widgetbook 2.0.x-beta` is currently not optimized for smaller devices. We are aiming to refactor the viewport controls by moving it into the toolbar in the top of the app. The items currently loacated in the toolbar will move into a collapsable (vertical) property panel which is similar to the panel known from design tools like Figma and Photoshop (see image).

Let us know what you think about the proposed changes.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/16862002/157899883-545507de-6a84-4461-964a-17c29f91dbe7.png">
