### ISSUE TITLE
Disable dragging and zooming of the preview area.

### ISSUE THREAD

**Issue by nullrocket** [widgetbook/widgetbook#139]
I'm not sure if this already exists, I couldn't find it if it does.  I would like to disable dragging and zooming of the device preview with the mouse, especially mouse wheel zooming.  It makes working with scrolling widgets pretty irritating as you can't use your wheel for scrolling within the widget being displayed, you also can't drag to scroll lists.  Zooming with a button/slider and / or a key combo would probably be a better option.

Just my opinion, but I've noticed a few other annoyances around dragging and zooming the device preview. While it is probably "seems" cool, its actually annoyed me enough that I would almost rather not use the tool. I've implement plenty of those kinds of features myself though so It is just opinion :).     

As far as dragging goes, unless you are planning on enabling multiple widgets on one screen and want to rearrange them I don't see the point of it being on all the time, I can see needing it  if you have zoomed and need to bring something into view, but again maybe some key combo to enable it would be better than hijacking input you would expect to go to the widget being previewed,    some kind of default alignment/positioning like left/right/center is probably right 90% of the time.

**Comment by nullrocket** [comment]
Well never mind, I didn't realize there was a 2.0.x-beta that did exactly what I was asking! Great work!

**Comment by JensHor** [comment]
Hey @nullrocket. thanks for the feedback! It's great to hear that you like the new features 👍🏻 We totally agree with your assessment and are looking forward to improve the toolbar further!
