### ISSUE TITLE
Grid Addon

### ISSUE THREAD

**Issue by jenshor** [widgetbook/widgetbook#17]
A user wished for a pixel grid to be able to approximate distances easier. An option to customise the distance between each grid line is required.

**Comment by bakeyevrus** [comment]
@jenshor are we talking about customizing the distance individually between each line? Let's say distance(l1, l2) = 20, but user can set distance(l2,l3) = 60, etc? Or it would be rather a slider that determines a size of a pixel (1x1, 2x2, etc)?

**Comment by jenshor** [comment]
It would probably be great if the user could specify horizontal and vertical line distance with a TextField. But before you start implementing something like this, we are currently working on a new version of Widgetbook (see the `widgetbook-3` branch) which renders the use-cases differently. We are aiming to have that version out soon 👍🏻

**Comment by bakeyevrus** [comment]
@jenshor, sure, I'll be implementing the feature on top of the `widgetbook-3` branch. Last time I wasn't able to compile it, but I'll try again and let you know.
