### ISSUE TITLE
Knob content carries over

### ISSUE THREAD

**Issue by fideldonson** [widgetbook/widgetbook#170]
**Description**
I have multiple use cases with text knobs. And when i change the text of the knob and switch to a new use case with the same type of knob (text) the content is carried over. Even if initial value is present.

**Steps To Reproduce**

1. create two use cases with text knobs
2. go to one and enter text in the knob
3. go to the other use case
4. See the previously entered text on the knob

**Expected Behavior**
I would expect the new use case to reset the knob.

**Comment by Auxx** [comment]
I'm experiencing the same issue.

**Comment by JensHor** [comment]
Thanks for raising this issue and giving feedback - we highly appreciate it 👍🏻 
We are not working on the fix.
