### ISSUE TITLE
Scroll movement gesture doesn't simulated

### ISSUE THREAD

**Issue by jttuboi** [widgetbook/widgetbook#185]
**Description**
In a list with SingleChildScrollView, the gesture of list movement doesn't work.
If it uses the scroll bar on right, works. But in my project, I don't use this scroll bar, only the gesture.
The gesture works in emulator.

- Flutter web and Flutter desktop
- Flutter 2.10.5.
- To test in Widgetbook, try to look the item 9 of the list without use the scrollbar on right. Try this on flutter web, flutter desktop.
```dart
      WidgetbookComponent(
        name: 'aaa',
        useCases: [
          WidgetbookUseCase(
            name: 'bbb',
            builder: (_) {
              return SizedBox(
                height: 50,
                child: Scrollbar(
                  child: SingleChildScrollView(
                    child: Column(
                      children: const [
                        Text('1                           .'),
                        Text('2                           .'),
                        Text('3                           .'),
                        Text('4                           .'),
                        Text('5                           .'),
                        Text('6                           .'),
                        Text('7                           .'),
                        Text('8                           .'),
                        Text('9                           .'),
                      ]))));})]),
```
- To check how the code works on emulator, it can use the code below.
```dart
void main() => runApp(MaterialApp(
    home: Scaffold(
        appBar: AppBar(),
        body: SizedBox(
            height: 50,
            child: Scrollbar(
                child: SingleChildScrollView(
                    child: Column(children: const [
              Text('1                           .'),
              Text('2                           .'),
              Text('3                           .'),
              Text('4                           .'),
              Text('5                           .'),
              Text('6                           .'),
              Text('7                           .'),
              Text('8                           .'),
              Text('9                           .'),
            ])))))));
```

**Screenshots**
In flutter desktop
![image](https://user-images.githubusercontent.com/376856/167711110-ff1b26d8-483e-4ac5-b718-5ca7f9bec73f.png)
In flutter web
![image](https://user-images.githubusercontent.com/376856/167712967-9c795112-0b0b-426c-aa79-f408b69a367e.png)
In emulator
![image](https://user-images.githubusercontent.com/376856/167712550-2fc710cf-36e5-4855-90d5-503d39aa5b9f.png)

**Comment by JensHor** [comment]
Hey @jttuboi, thanks for raising the issue. We are aware of this behaviour. In addition, we're expecting it to behave this way since Widgetbook is only an approximation of how the app looks and feels on a mobile device. Therefore, for scrolling, the app behaves similar to a Flutter Web/Desktop application.

Nonetheless, it is interesting to get to know why you'd like it to behave similar to the iOS simulator. Is there a specific scenario you'd like to test or is it just unfamiliar to use the scrollbar or mouse weel/scroll?

**Comment by JensHor** [comment]
I'm setting this issue to _won't fix_ for now, but i'm looking forward to the discussion 👍🏻

**Comment by jttuboi** [comment]
> Hey @jttuboi, thanks for raising the issue. We are aware of this behaviour. In addition, we're expecting it to behave this way since Widgetbook is only an approximation of how the app looks and feels on a mobile device. Therefore, for scrolling, the app behaves similar to a Flutter Web/Desktop application.
> 
> Nonetheless, it is interesting to get to know why you'd like it to behave similar to the iOS simulator. Is there a specific scenario you'd like to test or is it just unfamiliar to use the scrollbar or mouse weel/scroll?

Hi @JensHor, yes it was until I discovered 1 day ago about mouse wheel 😅.

In the company project I work, I use the Widgetbook to show the components what we create for consulting after or for other people in the company need to look how works it.

When I open this issue, I was creating a dropdown. In my dropdown, when shows the list, it doesn't have the scrollbar, so we can't look how works there. But 1 day ago I finished the dropdown and when I updated the Widgetbook, I realized about scroll wheel.

So, I think it's oks to close this issue if you want. Thanks. 😄
