### ISSUE TITLE
BottomSheet is showing up in Widgetbook instead of simulated app

### ISSUE THREAD

**Issue by JensHor** [widgetbook/widgetbook#190]
**Description**
Currently when trying to call openBottomSheet and pass the context from the usecase it will display the bottomsheet in the entire website instead of inside the mobile preview.

**Comment by JensHor** [comment]
From discord user:

Also noticed other weird behaviors now with bottomsheets.

Had a input field with overridden theme from context but it seems to ignore those style.

![image](https://user-images.githubusercontent.com/16862002/169812809-cf4acf86-d206-4372-a236-e2f111992e27.png)

**Comment by tieorange** [comment]
This solution does not work with bottom sheet

It still is drawn outside of the device frame

Code:
`final result = await showModalBottomSheet(
    isScrollControlled: true,
    shape: const RoundedRectangleBorder(
      borderRadius: BorderRadius.vertical(top: Radius.circular(15)),
    ),
    barrierColor: kcBottomSheetBarrierColor,
    backgroundColor: kcWayfinderWhite,
    context: context,
    useRootNavigator: false,
    builder: (context) => child,
  );`
