### ISSUE TITLE
is knobs with widgetbook generator implemented ?

### ISSUE THREAD

**Issue by kgaulin** [widgetbook/widgetbook#205]
**Description**
The getter 'knobs' isn't defined for the type 'BuildContext' with the annotation @WidgetbookUseCase

**Steps To Reproduce**

1. create a widget

```
class Heading extends StatelessWidget {
  final String text;
  const Headingt({Key? key, required this.text}) : super(key: key);

  @override
  Widget build(BuildContext context) {

    return Text(
      text,
      style: Theme.of(context).textTheme.headline1,
    );
  }
}
```
2. add usecase
```
@WidgetbookUseCase(name: 'H2' , type: Heading)
Widget h2Case(BuildContext context) =>  Heading(text: context.knobs.text(
  label: 'Title Label',
  initialValue: 'HomePage',
));
```

**Expected Behavior**
i want to be able to add knob when i use widgetbook generator

**Screenshots**
![image](https://user-images.githubusercontent.com/68933242/170916551-3a2ef5c2-4f33-4366-b915-447c8421c361.png)

**Comment by JensHor** [comment]
You are likely seeing this problem because you just imported `package:widgetbook_annotation` but did not import `package:widgetbook`. 

The extension method which makes `knobs` available from `context` is defined and exported in the `widgetbook` package. I see that this is confusing and the docs must be improved. However, it will be unlikely that we'll export the `widgetbook` package within `widgetbook_annotation` package, since `widgetbook_annotation` is added as a (production) dependency while the `widgetbook` package is added as a dev dependency.

**Comment by kgaulin** [comment]
Hi JensHor, thank you for the fast answer. I tried to import package:widgetbook_annotation with package:widgetbook_annotation or only package:widgetbook. knobs is now discover but i have a issue with the annotation.  Annotation must be either a const variable reference or const constructor invocation.

my pubspec :
```
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  widgetbook_annotation: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  widgetbook: ^2.3.0
  widgetbook_generator: ^2.2.0
  build_runner: ^2.1.11
```
and my widget

```
import 'package:flutter/material.dart';
import 'package:fun_learning/widgets/enums/heading_type.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart';
import 'package:widgetbook/widgetbook.dart';


class HeadingText extends StatelessWidget {
  final String text;
  final HeadingType heading;

  const HeadingText({Key? key, required this.text, this.heading = HeadingType.h1}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    TextStyle? style;

    switch(heading) {
      case HeadingType.h1:
        style = Theme.of(context).textTheme.headline1;
        break;
      case HeadingType.h2:
        style = Theme.of(context).textTheme.headline2;
        break;
      case HeadingType.h3:
        style = Theme.of(context).textTheme.headline3;
        break;
      case HeadingType.h4:
        style = Theme.of(context).textTheme.headline4;
        break;
      case HeadingType.h5:
        style = Theme.of(context).textTheme.headline5;
        break;
    }

    return Text(
      text,
      style: style,
    );
  }
}


@WidgetbookUseCase(name: 'H1' , type: HeadingText)
Widget h1Case(BuildContext context) =>  HeadingText(text: context.knobs.text(
  label: 'Title Label',
  initialValue: 'HomePage',
));

@WidgetbookUseCase(name: 'H2' , type: HeadingText)
Widget h2Case(BuildContext context) =>  const HeadingText(text: 'Heading Text', heading: HeadingType.h2);

@WidgetbookUseCase(name: 'H3' , type: HeadingText)
Widget h3Case(BuildContext context) =>  const HeadingText(text: 'Heading Text', heading: HeadingType.h3);

@WidgetbookUseCase(name: 'H4' , type: HeadingText)
Widget h4Case(BuildContext context) =>  const HeadingText(text: 'Heading Text', heading: HeadingType.h4);

@WidgetbookUseCase(name: 'H5' , type: HeadingText)
Widget h5Case(BuildContext context) =>  const HeadingText(text: 'Heading Text', heading: HeadingType.h5);
```

**Comment by Lightgaming** [comment]
@kgaulin your solution works for me! 🕺

**Comment by Hari-07** [comment]
> You are likely seeing this problem because you just imported `package:widgetbook_annotation` but did not import `package:widgetbook`.
> 
> The extension method which makes `knobs` available from `context` is defined and exported in the `widgetbook` package. I see that this is confusing and the docs must be improved. However, it will be unlikely that we'll export the `widgetbook` package within `widgetbook_annotation` package, since `widgetbook_annotation` is added as a (production) dependency while the `widgetbook` package is added as a dev dependency.

Could we get the knobs property into widgetbook generator then?

**Comment by kgaulin** [comment]
I just found the solution for me ! 

i had a naming conflict for decorator WidgetbookUseCase between widgetbook_annotation.dart and widgetbook.dart, then i put a alias to  widgetbook.dart and now it's working.

![image](https://user-images.githubusercontent.com/68933242/184448569-0c228064-86df-49d1-a620-7b15d77d6ec4.png)

**Comment by Hari-07** [comment]
I was able to do that too, but if not for knobs widgetbook doesn't need to be a dependency, dev dependency is enough

**Comment by Lightgaming** [comment]
This is how we solved it:

```dart
// ignore_for_file: depend_on_referenced_packages

import 'package:flutter/material.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbookKnobs;

@widgetbookKnobs.WidgetbookUseCase(name: 'Enter your Name', type: EnterYourName)
Widget helloWorld(BuildContext context) {
  final name = context.knobs.text(label: 'User Input');
  return Center(
    child: Text('Your Name: ${name}'),
  );
}
```
