### ISSUE TITLE
Proposal: Knobs for models

### ISSUE THREAD

**Issue by jenshor** [widgetbook/widgetbook#227]
# Proposal: Knobs for models

| Legend         |
| -------------- |
| 🎛 Knob        |
| 📦 (Data)Model |
| ⛓ Property of model |
| 💎 Component/Widget |

## Related proposals

- https://github.com/widgetbook/widgetbook/issues/228

## Description

As a developer, I want to be able to create a `🎛 modelKnob`, so I can compose the values of multiple primary knobs (and/or `🎛 modelKnob`s) to represent a model.

For example, a `📦 ChatMessage` model contains of a `📦 UserProfile` and a `📦 Message` model. The `📦 UserProfile` model has properties for `⛓ firstName`, `⛓ lastName`, and `⛓ imageUrl`. The `📦 Message` model has properties for `⛓ content` and `⛓ id`.

```bash
└── 📦 ChatMessage
    ├── 📦 UserProfile
    │   ├── ⛓ firstName
    │   ├── ⛓ lastName
    │   └── ⛓ imageUrl
    └── 📦 Message
        ├── ⛓ content
        └── ⛓ id
```

Lets assume that the `💎 ChatMessageComponent` accepts a `📦 ChatMessage` model as a parameter. `💎 ChatMessageComponent` is composed of a `💎 UserProfileComponent` and a `💎 MessageComponent`. `💎 ChatMessageComponent` forwards the appropriate models to the components.

```bash
└── 💎 ChatMessageComponent
    ├── 📦 ChatMessage
    ├── 💎 UserProfileComponent
    │   └── 📦 ChatMessage.UserProfile
    │       ├── ⛓ firstName
    │       ├── ⛓ lastName
    │       └── ⛓ imageUrl
    └── 💎 MessageComponent
        └── 📦 ChatMessage.Message
            ├── ⛓ content
            └── ⛓ id
```

While this example might be rather simple, a `WidgetbookUseCase` with knobs for all the properties can quickly become hard to understand and is rather abstract from the actual implementation.

```bash
└── Knobs Panel
    ├── 🎛 ⛓ firstName
    ├── 🎛 ⛓ lastName
    ├── 🎛 ⛓ imageUrl
    ├── 🎛 ⛓ content
    └── 🎛 ⛓ id
```

## Proposal

I propose the ability to specify knob-driven models:

```dart
@WidgetbookModel
UserProfile buildUserProfile(
  BuildContext context,
  String label,
  String? description,
) {
  return context.knobs.modelKnob<UserProfile>(
    label: label,
    description: description,
    builder: (context) {
      return UserProfile(
        firstName: context.knobs.textKnob(...),
        lastName: context.knobs.textKnob(...),
        imageUrl: context.knobs.textKnob(...),
      );
    },
  );
}
```

The above implementation proposes a new `🎛 modelKnob` which defines a builder function to compose any model from primary knobs or `🎛 modelKnob`.

The user interface within Widgetbook will now show a group which represents the whole model. Within the group, the user interface shows the underlying primary or `🎛 modelKnob`s.

```bash
└── Knobs Panel
    └── 🎛 📦 UserProfile
        ├── 🎛 ⛓ firstName 
        ├── 🎛 ⛓ lastName 
        └── 🎛 ⛓ imageUrl 
```

The `@WidgetbookModel` annotation is used to mark this model for automatic code generation (see https://github.com/widgetbook/widgetbook/issues/228). This allows the code generator to match parameters of `Widget`s with knob-driven models.

### Nested models

As stated above, the `🎛 modelKnob` needs to be composable of primary knobs and `🎛 modelKnob`s.

Defining a nested model might look like this:

```dart
@WidgetbookModel
UserProfile buildUserProfile(
  BuildContext context,
  String label,
  String? description,
) {
  return context.knobs.modelKnob<UserProfile>(    
    label: label,
    description: description,
    builder: (context) {
      return UserProfile(
        firstName: context.knobs.textKnob(...),
        lastName: context.knobs.textKnob(...),
        imageUrl: context.knobs.textKnob(...),
      );
    },
  );
}

@WidgetbookModel
Message buildMessage(
  BuildContext context,
  String label,
  String? description,
) {
  return context.knobs.modelKnob<Message>(
    label: label,
    description: description,
    builder: (context) {
      return Message(
        content: context.knobs.textKnob(...),
        id: context.knobs.textKnob(...),
      );
    },
  );
}

@WidgetbookModel
ChatMessage buildChatMessage(
  BuildContext context,
  String label,
  String? description,
) {
  return context.knobs.modelKnob<ChatMessage>(
    label: label,
    description: description,
    builder: (context) {
      return ChatMessage(
        userProfile: buildUserProfile(context, label: 'userProfile'),
        message: buildMessage(context, label: 'message'),
      );
    },
  );
}
```

The knobs panel within Widgetbook will now look like this:

```bash
└── 🎛 📦 ChatMessage
    ├── 🎛 📦 UserProfile
    │   ├── 🎛 ⛓ firstName
    │   ├── 🎛 ⛓ lastName
    │   └── 🎛 ⛓ imageUrl
    └── 🎛 📦 Message
        ├── 🎛 ⛓ content
        └── 🎛 ⛓ id
```

In comparison to the current flat knob hierarchy, this is rather complex and might be hard to implement in a way that it is not confusing. However, in contrast, this clearly documents in Widgetbook how the structure of the data model is organized.
Therefore, I argue that this structure might be great to understand how the Widget is build. For designers (and developers alike), I propose that a button is introduced to allow toggling between the flat and tree-like presentation.

## Rate the proposal

As you might know, our team at Widgetbook loves feedback 💙 Therefore, please feel free to rate this proposal by using the reaction buttons. If a proposal like this reaches enough likes we can move it up within our roadmap 🚀

Make sure to hit 👍🏻 if you'd like to see this implemented soon.

Make sure to hit 👎🏻 if you think this proposal is a bad idea.

We appreciate both types of feedback, but in case you hit 👎🏻 let us know why! If you have an idea on how to improve this proposal, please let us know in the comments 💬

**Comment by YoussefRaafatNasry** [comment]
This issue is no longer valid after Widgetbook 3, as we support [custom knobs](https://docs.widgetbook.io/knobs/custom-knob).
