### ISSUE TITLE
Proposal: Variants

### ISSUE THREAD

**Issue by jenshor** [widgetbook/widgetbook#228]
# Proposal Variants

Widgetbook currently only features an option to create use-cases, which are a specific set of parameters for a _visual test-case_.

Recently the Widgetbook team introduced knobs which now allows to mix fixed parameters with interchangable parameters driven by knobs.

This allows for more flexibility but is also confusing regarding the feature sets. This proposal aims to introduce a new feature set which separates use-cases with fixed parameters from knob-driven variants.

## Related proposals

- https://github.com/widgetbook/widgetbook/issues/227

## Description

As a developer, I want to be able to create a _Variant_ of a _Component_. This functionality would be similar to the Component and Variant feature known from Figma. In Figma a component might have multiple properties (similar to e.g. constructor parameters in Dart) which change the appearance of a Component. 

I think the knob feature perfectly aligns with Variations of a Figma Component since knobs allow Developer and Designer to change between different configurations of the Component/`Widget` while use-cases define more rigid cases.

## Proposal

I propose to extend the use-case feature by an additional feature set _Variant_ which is mainly code-generator and knobs driven.

Right now, it is quite time consuming to create use-cases for Widgets because the developer has to think about how the Widget works and then implement one or multiple use-cases. While `widgetbook_generator` helps with maintenance, we refrained from using the generator to create use-cases.

Since use-cases are also visual test-cases, it is hard to guess which parameters of a Widget are actually meaningful and make sense. For instance, an `int` parameter could only be valid for negative values. Detecting and automatically generating use-cases is therefore challenging.

However, with [Proposal: Knobs for models](https://github.com/widgetbook/widgetbook/issues/227) I think generating Variants via `widgetbook_generator` is highly attractive and makes Widgetbook more accessible for frontend teams due to reduced manual coding.

### WidgetbookVariant

I propose to add `WidgetbookVariant` which works like `WidgetbookUseCase` but has a different style within the user-interface of Widgetbook. This separates use-cases from variants. Similar to `WidgetbookUseCase`, `WidgetbookVariant` is a child element of `WidgetbookComponent` within the navigation tree.

### Annotation for code generation

In addition, I propose to introduce the `@WidgetbookComponent` annotation (name might change due to a potential naming conflict with `WidgetbookComponent` from package `widgetbook`):

```dart
@WidgetbookComponent
class ButtonComponent extends StatelessWidget {
  const ButtonComponent._({
    Key? key,
    required this.color,
    required this.text,
  }) : super(key: key);

  const ButtonComponent.primary({
    required String text,
  }) : this._(
          color: Colors.blue,
          text: text,
        );

  const ButtonComponent.secondary({
    required String text,
  }) : this._(
          color: Colors.green,
          text: text,
        );

  const ButtonComponent.danger({
    required String text,
  }) : this._(
          color: Colors.red,
          text: text,
        );

  final Color color;
  final String text;

  @override
  Widget build(BuildContext context) {
    return ColoredBox(
      color: color,
      child: Text(text),
    );
  }
}
```

The `@WidgetbookComponent` annotation marks a `Widget` to be computed by the code generator. Via code analysis, the constructors and it's parameter and parameter types are extracted and matched against available knobs. This includes model knobs, which can be extracted based on the `@WidgetbookModel` annotation. After matching parameters with knobs, the generator creates one variant for each (public) constructor.

### Parameter matching

Matching primary parameters to knobs is simple in itself and can be computed based on types. The `label` of a knob is extracted from the parameter name. The `description` of the knob can be extracted from the parameter documentation, if the parameter is named.

However finding good, relevant and valid default values for these knobs can be challenging. Therefore, we propose a syntax similar to the one used in [freezed ](https://pub.dev/packages/freezed) where developers define Knob default values with a `@KnobDefault` annotation. The private constructor of our button now looks like this:

```dart
  const ButtonComponent._({
    Key? key,
    required this.color,
    @KnobDefault('Press me') required this.text,
  }) : super(key: key);
```

### Unmatched Models

Some `Widget` might require more complex data where passing primary types is replaced by just passing a model object instead. [Proposal: Knobs for models](https://github.com/widgetbook/widgetbook/issues/227) already allows for creating more complex model-based knobs. However, there is likely a case where no model knob matches a required parameter (e.g. a developer forgot to define one). In this case I see two ways of implementing this:

1. Abort code generation and throw an error
1. Build a model using code analysis and code generation by breaking down models until a model only consists of primary types which can be represented by primary types.

Case 1 is obviously trivial to implement but limits accessibility of Widgetbook. 

Case 2 is complex to implement and the result might be an extremely nested model which is hard to visualize in the user interface of Widgetbook.

Therefore, I propose the following:
Implement Case 2 and limit nested models to a tree depth (likely 2 or 3 levels). Throw an error if model depth is reached. In addition, also show a warning that no knob match has been found so the developer is aware that a model should be created.

In Case 2 the problem of finding proper values for the model parameters applies as well. The only option is to default to e.g. the empty string `''` for the textKnob, `0` for the `int` knob, etc and hope for the best. In addition, a warning is shown that a default knob value has been assumed.

## Advantages of the proposal

Instead of defining multiple use-cases and mock different data objects from models for each use-case, the developer just annotates the components and adds _one_ knob implementation for each model. 

Therefore, the generator creates Variants using the knob-driven models making Widgetbook easier to use for frontend teams.

## Rate the proposal

As you might know, our team at Widgetbook loves feedback 💙 Therefore, please feel free to rate this proposal by using the reaction buttons. If a proposal like this reaches enough likes we can move it up within our roadmap 🚀

Make sure to hit 👍🏻 if you'd like to see this implemented soon.

Make sure to hit 👎🏻 if you think this proposal is a bad idea.

We appreciate both types of feedback, but in case you hit 👎🏻 let us know why! If you have an idea on how to improve this proposal, please let us know in the comments 💬

**Comment by YoussefRaafatNasry** [comment]
This issue will be closed due to conflict with Widgetbook 4 plan.
