### ISSUE TITLE
fix: material text field label not showing correctly

### ISSUE THREAD

**Issue by jenshor** [widgetbook/widgetbook#249]
**Description**
The `label` of the `TextField` does not render correctly in widgetbook. This might be a Theme problem. 

**Screenshots**

Simulator:
![image](https://user-images.githubusercontent.com/16862002/178221968-8d40cfe8-d28e-43e0-a137-9211959c5045.png)

Widgetbook:
![image](https://user-images.githubusercontent.com/16862002/178222010-54d6e79e-005c-452f-a842-cc820ed33731.png)

**Comment by jenshor** [comment]
Hey @Solano-Furlan, we know this is important to you but haven't had the time to look into this. We hope to be able to tackle this next week.

**Comment by adrianostas** [comment]
@jenshor Any updates on this?Thanks.

**Comment by jenshor** [comment]
Sorry that we haven't been around to solve the problem. I just looked into the problem on our most recent beta version and I cannot longer reproduce the problem.

**Screenshot:**

<img width="518" alt="image" src="https://user-images.githubusercontent.com/16862002/217022858-dcdc6d4d-8820-4d51-94bc-39f84a7f1af9.png">

**Code (using `widgetbook_generator`)**

```
@WidgetbookUseCase(name: 'Bugfix', type: TextField)
Widget textFieldBugFix(BuildContext context) {
  return const TextField(
    decoration: InputDecoration(
      label: Text('This is a label'),
      hintText: 'Placeholder',
    ),
  );
}
```

**Comment by jenshor** [comment]
Since we are currently unable to reproduce the bug I'm closing this issue for now, but please feel free to reopen this issue if you have additional information or if you have code with which we can reproduce the problem.
