### ISSUE TITLE
refactor: Widgetbook 3.0

### ISSUE THREAD

**Issue by jenshor** [widgetbook/widgetbook#284]
# Widgetbook 3.0

The current Widgetbook version has some problems and hard-to-fix bugs. Especially the functionality around the `device_frame`, Widgetbook Frame, and `none` frames are confusing. 
In addition, the builder functions are unintuitive. 

Widgetbook might see some breaking changes to make this happen. 

## `AddOn`s

The Property Panel is cumbersome and will be replaced by a context-menu-based `AddOn` implementation, making Widgetbook more customizable. 

Planned `AddOn`s:
### Theme AddOn 
Similar to what is currently available

### Device or Preview AddOn 
The implementation of Frames and Devices does not make a lot of sense and is quite confusing to use. The Widgetbook and Device Frame share the devices. However, Device Frame uses different models than Widgetbook Frame. In addition, the `none` frame does not use Devices at all and operates independently of what has been selected within the Property Panel. Since the devices are mainly `MediaQuery` driven, we might see that this `AddOn` will also feature the `TextScaleFactor` and `Orientation` property settings.
- #17 
- #72
- #119 
- #164
- #165
- #217
- #250
### Localization AddOn
- #232 

### Theme AddOn
- #249

# Settings
- #171 
- #230

## Navigation
- #61
- #62 
- #65 Implementation for generator might come later

## Hot Reloading
- #4 
- #12 and #50

**Comment by hampsterx** [comment]
hi @jenshor any update to this/v3? :)

**Comment by YoussefRaafatNasry** [comment]
Since v3.0.0 is already released, I will be closing this for less clutter, and track the open issues individually.
