### ISSUE TITLE
PageBuilder slide behaviour seems to not work

### ISSUE THREAD

**Issue by Franpastoragusti** [widgetbook/widgetbook#330]
Thanks for the package! It's so cool comming from other tech to have a package like that.

I'm rendering a PageBuilder component used to make an slider, in real devices the slide behavior works but when I run it on widgetbook on macos or browser, the slide effect seems to not be detected..

**Comment by jenshor** [comment]
Thanks for the feedback. We'll look into this 🚀
Do you mind sharing a simple code snippet on which `Widget` you are trying to use?
