### ISSUE TITLE
Download request fails (widgetbook.io)

### ISSUE THREAD

**Issue by jayjah** [widgetbook/widgetbook#34]
I just want to inform you it's not possible to request a download from the following homepage: `https://widgetbook.io`.

The following error occurred after press on Get Access: 
`Oops! Something went wrong while submitting the form.`

The following error is visible in the console:
```
GET https://firecrown.us1.list-manage.com/subscribe/post-json?u=34ac9ff90651cadf6f31835ab&amp;id=363df7e9b9&c=jQuery351047704463576119527_1634213232985&FNAME=Markus&SNAME=Krebs&EMAIL=markuskrebs93%40gmail.com&b_34ac9ff90651cadf6f31835ab_363df7e9b9=&_=1634213232986 net::ERR_ABORTED 503
```

**Comment by JensHor** [comment]
Yes. It's a link-forward with an opt-in for our newsletter to get notified when new features land. It seems that mailchimp currently has some server problems resulting in the message. We hope it will get fixed soon. 👍🏻

**Comment by Lucas-ctrl1** [comment]
Mailchimp fixed the problem. It‘s now possible again to submit the form.

**Comment by jayjah** [comment]
Yes, I can confirm this. I received the newsletter mail recently!
