### ISSUE TITLE
Issue: Widgetbook and GoRoute

### ISSUE THREAD

**Issue by tot14883** [widgetbook/widgetbook#342]
I found a issue about widgetbook and GoRoute below:
```Because widgetbook >=2.0.6-beta depends on go_router ^3.0.5 and application depends on go_router ^5.1.1, widgetbook >=2.0.6-beta is forbidden.
So, because application depends on widgetbook 2.4.1, version solving failed.
pub get failed (1; So, because application depends on widgetbook 2.4.1, version solving failed.)
```

How to fix this?

**Comment by kmomimomi** [comment]
I have the same problem.  go_router v5 has some breaking changes, so it doesn't seem possible to simply upgrade.

[Related go_router issue](https://github.com/flutter/flutter/issues/108044)
[GoRouter v5 migration guide](https://docs.google.com/document/d/10l22o4ml4Ss83UyzqUC8_xYOv_QjZEi80lJDNE4q7wM/edit?pli=1&resourcekey=0-U-BXBQzNfkk4v241Ow-vZg)

**Comment by kmomimomi** [comment]
For now, I was able to solve it by dependency_override.

Add following line to pubspec.yml
- myproject/pubspec.yml
```yml
dependency_overrides:
  widgetbook:
    path: ./widgetbook_patch/
```

Copy widgetbook 24.1 to myproject/widgetbook_patch. and add following line.
- widgetbook_patch/pubspec.yml
```yml
dependencies:
  go_router: ^5.0.0 // change version.
```

- widgetbook_patch/widgetbook.dart (line 363)
```dart
      child: MaterialApp.router(
        routeInformationProvider: goRouter.routeInformationProvider, // add this
        routeInformationParser: goRouter.routeInformationParser,
        routerDelegate: goRouter.routerDelegate,
        title: widget.appInfo.name,
        themeMode: ThemeMode.dark,
        debugShowCheckedModeBanner: false,
        darkTheme: Styles.darkTheme,
        theme: Styles.lightTheme,
      ),
```
[cf. GoRouter v4 breaking change](https://docs.google.com/document/d/1T2LmzMj5HpD7hEexXL4Xz6vqoJD81bEGaa9NsV24faw/edit?resourcekey=0-PuQbtDVl7ZabpJ2B9AHWUg#)

- widgetbook_patch/lib/src/rendering/builders/app_builder.dart (line 25)
```dart
Widget _defaultAppBuilderMethod(BuildContext context, Widget child) {
  final _router = getRouter(child);
  return WidgetsApp.router(
    color: Colors.transparent,
    builder: (context, childWidget) {
      return childWidget ?? child;
    },
    routeInformationProvider: _router.routeInformationProvider, // add this line
    routeInformationParser: _router.routeInformationParser,
    routerDelegate: _router.routerDelegate,
  );
}
```

- widgetbook_patch/lib/src/navigation/router.dart
```dart
GoRouter createRouter<CustomTheme>({
  required WorkbenchProvider<CustomTheme> workbenchProvider,
  required PreviewProvider previewProvider,
}) {
  final router = GoRouter(
    redirect: (context, routerState) { // add 'context'
      final theme = routerState.queryParams['theme'];
      final locale = routerState.queryParams['locale'];
      final device = routerState.queryParams['device'];
      final textScaleFactor = routerState.queryParams['text-scale-factor'];
      final orientation = routerState.queryParams['orientation'];
      final frame = routerState.queryParams['frame'];
      final path = routerState.queryParams['path'];
```
[cf. GoRouter v5 migration guide](https://docs.google.com/document/d/10l22o4ml4Ss83UyzqUC8_xYOv_QjZEi80lJDNE4q7wM/edit?pli=1&resourcekey=0-U-BXBQzNfkk4v241Ow-vZg)

Sorry, this worked in my project but I haven't tested it.

**Comment by pansitwattana** [comment]
Please migrate to `go_router: 5.1.1`

`Because widgetbook 2.4.1 depends on go_router ^3.0.5 and no versions of widgetbook match >2.4.1 <3.0.0, widgetbook ^2.4.1 requires go_router ^3.0.5.`

**Comment by SilentCatD** [comment]
Please migrate to go_router ^6.0.0.
``Because widgetbook >=3.0.0-beta.1 depends on go_router ^5.2.1 and my_project depends on go_router ^6.0.0, widgetbook >=3.0.0-beta.1 is forbidden``

**Comment by uno-sw** [comment]
Ideally, I think navigation should be implemented in widgetbook itself without go_router, just like bloc package was replaced in the past (#28). Any plans to do so?

**Comment by jenshor** [comment]
> Ideally, I think navigation should be implemented in widgetbook itself without go_router, just like bloc package was replaced in the past (#28). Any plans to do so?

I totally and in the far future we are also aiming to do so. However, we think this will slow down development as it'll make the package harder to maintain. Therefore, we'll keep the dependency for now.

**Comment by jenshor** [comment]
We just merged a PR that bumps go_router version to the most recent and fixes general navigation problems. 

We'll now add tests and release a new Widetbook version next week. Stay tuned!

**Comment by chief-nerd** [comment]
And this issue again ...
```
Because widgetbook >=2.0.6-beta <3.0.0-beta.1 depends on go_router ^3.0.5 and your_app depends on go_router ^6.2.0, widgetbook >=2.0.6-beta <3.0.0-beta.1 is forbidden.
```
