### ISSUE TITLE
fix: `widgetbook` does not work with `flutter_screen_utils`

### ISSUE THREAD

**Issue by jenshor** [widgetbook/widgetbook#347]
**Description**
For more context see: https://discord.com/channels/879618555560218625/879725652612374549/1032676427763568731

**Comment by shigomany** [comment]
I'm currently trying to make screenutils friends with widgetbook. There are the following problems:

1. There is not enough callback function or access to the current device that was selected with `Devices`. So ScreenUtils takes the resolution from the `MediaQuery.fromWindow` or `MediaQuery.of(context)` depending on the `useInheritedMediaQuery` parameter (works on ScreenUtilsInit - widget and screen utils 5.6.0)
2. If the first problem can be solved through a variable in State, the dimensions are set (according to the size of the device in mediaQuery and in ScreenUtil), but if your widget has a state that changes for example by clicking, then the dimensions in ScreeUtil are set according to the size of the application screen.

**Comment by shigomany** [comment]
I can make a visual example in github or record a video or both)

**Comment by shigomany** [comment]
But if i adding inside build method in `CounterContainer` everything works well:
```dart
ScreenUtil.init(context, minTextAdapt: true);
```

**Comment by jenshor** [comment]
Sorry that it took a while until we've been able to work on this. Due to #450, we are certain that the `MediaQuery` is now correctly applied regarding the selected `device`. In addition, you can now access the selected device by using `context.device` within the `appBuilder`. 

Will this already solve the problem?

**Comment by shigomany** [comment]
So I will close this issue

**Comment by YoussefRaafatNasry** [comment]
Due to the rewrite of the Addons API, Widgetbook now works with `flutter_screenutil` like a charm.
This is scheduled to be released soon.
