### ISSUE TITLE
feat: Multiline text knob

### ISSUE THREAD

**Issue by aloisdeniel** [widgetbook/widgetbook#373]
**Description**

I would love to have a multiline option on the `text` knob.

```dart
 final code = context.knobs.text(
      label: 'Code',
      multiline: true,
      initialValue: '''// Headers
for (var level = 1; level <= 6; level++)
  AppHeaderBlot(
    level: level,
    child: defaultText,
  ),''',
 
    );
```

**Comment by jenshor** [comment]
Hey Aloïs, thanks for submitting this feature request. We just merged a PR that added this functionality. The new version is published as widgetbook 3.0.0-beta.x. As of now, there are no docs or migration docs available for Widgetbook 3, but we are quickly moving forward to publishing the docs. If you are using `widgetbook_generator` migration effort could be minimal.

I'll close this for now as it's already fixed. If you have additional feedback, feel free to re-open the issue 👍🏻
