### ISSUE TITLE
feat: Routing by URI for use cases

### ISSUE THREAD

**Issue by aloisdeniel** [widgetbook/widgetbook#381]
**Description**

Currently, navigation in the book isn't reflected in the browser navigation bar when hosting a Widgetbook online. 

I would love to have the possibility to share a direct link like `https://mywidgetbook.com/#Widgets/Core/Button` to a specific use case (_for example for linking a widget use case to a project task in ClickUp_).

**Comment by jenshor** [comment]
Hey Aloïs, thanks for raising this issue. We just merged a PR that handles this problem. The new version is published as `widgetbook` `3.0.0-beta.x`. As of now, there are no docs or migration docs available for Widgetbook 3, but we are quickly moving forward to publishing the docs. If you are using `widgetbook_generator` migration effort could be minimal. 

I'll close this for now as it's already fixed. If you have additional feedback, feel free to re-open the issue 👍🏻
