### ISSUE TITLE
[widgetbook_annotation] not rendering correct device Frame

### ISSUE THREAD

**Issue by socramm9** [widgetbook/widgetbook#385]
**Description**
I am running a basic widgetbook_annotation configuration 
```

import 'package:flutter/material.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart';

@WidgetbookTheme(name: 'Dark', isDefault: true)
ThemeData darkTheme() => ThemeData.dark();
@WidgetbookTheme(name: 'light')
ThemeData lightTheme() => ThemeData();

@WidgetbookApp.material(
  name: 'Meal App',
  foldersExpanded: true,
  widgetsExpanded: true,
  frames: [
    WidgetbookFrame(
      name: 'Device Frame',
      allowsDevices: true,
    ),
    WidgetbookFrame(
      name: 'Widgetbook',
      allowsDevices: true,
    ),
  ],
  devices: [
    Apple.iPhone13,
    Apple.iPadPro10Inch,
  ],
)
class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp();
  }
}

```

iPhone13 is configured as device. But if I run the generated code it look like this:

<img width="2101" alt="Bildschirm­foto 2022-12-13 um 21 31 13" src="https://user-images.githubusercontent.com/52098754/207437835-76fc52be-7fbd-45b0-9134-4cb7ae15a4c4.png">

Before using widgetbook_annotation I tried using the manual configuration ad it was Rendering the device frame correctly.

Am I missing something?

**Comment by jenshor** [comment]
Just tested this on our most recent release which is `widgetbook` `3.0.0-beta.8` and this seem to work. The are working hard on a documented stable release, so stay tuned!
<img width="1684" alt="image" src="https://user-images.githubusercontent.com/16862002/217213062-626bf782-4609-41af-99b1-1c154ea4336d.png">

However, note that the `DeviceFrame` library does not support all phones, so e.g. the "iPhone 13 Pro" is not supported. Therefore, the generic phone (which is shown in the screenshot of the issue) is shown instead. 

I'm closing this issue, but if you have additional feedback feel free to reopen it.
