### ISSUE TITLE
WidgetbookComponent doesn't exist.

### ISSUE THREAD

**Issue by lukaszciastko-spica** [widgetbook/widgetbook#399]
**Description**

WidgetbookComponent does not exist.

**Steps To Reproduce**

Run the Example from pub.dev.

You can also follow the [Setup](https://docs.widgetbook.io/widgetbook/setup) documentation.

**Comment by jenshor** [comment]
Hey Lucas, thanks for raising this issue. What version are you using for `widgetbook`?

**Comment by jenshor** [comment]
I think this problem was introduced by me publishing a package with a wrong version increment. We unpublished the package and the problem should be gone. 

If this still exists feel free to re-open the issue 👍🏻
