### ISSUE TITLE
Story names do not update on web

### ISSUE THREAD

**Issue by jenshor** [widgetbook/widgetbook#4]
# How to reproduce

1. Create a `Story` with a name (e.g. 'Test')
2. Start the `Widgetbook`
3. Observe that the `Story` is shown as 'Test' 
4. Change the name (e.g. to 'Test2')
5. Hot reload the `Widgetbook`
6. Observe that the Story is shown as 'Test'. **Expected**: 'Test2'

This problem only occurs on web. E.g. on the Chrome browser.

**Comment by JensHor** [comment]
Hot restarting in flutter web is actually a hot restart (see https://github.com/flutter/flutter/issues/53041). Therefore, hot reloading for flutter web will be supported when the fix for https://github.com/flutter/flutter/issues/53041 lands.

**Comment by jenshor** [comment]
Hot restarting works quite well with the query parameters of the go_router implementation. Closing this issue as it works sufficiently.

**Comment by iam-yan** [comment]
> Hot restart (web) is not working for me at all with `widgetbook 2.4.1`. If I run any widgetbook ([this one, for example](https://docs.widgetbook.io/widgetbook/overview#usage)), make any change (Widgetbook, or builder, doesn't matter) and trigger a hot restart, the page refreshes, but the changes are not reflected.

Same here. I have to stop the app and run it again to see any updates applied.
