### ISSUE TITLE
WidgetbookTheme does not exist.

### ISSUE THREAD

**Issue by lukaszciastko-spica** [widgetbook/widgetbook#401]
**Description**

WidgetbookTheme does not exist.

**Steps To Reproduce**

Run the Example from pub.dev.

You can also follow the [Setup](https://docs.widgetbook.io/widgetbook/setup) documentation.

**Comment by jenshor** [comment]
What version are you using for `widgetbook`?

**Comment by Okunamutata** [comment]
This is happening on version 2.4.1

**Comment by Knupper** [comment]
I have the same problem with version 2.4.1, the only difference is that the Widgetbook.Frame class is missing

Maybe the reason is that the widgetbook_models in version 0.0.8 does not support this files?

```
pub-cache/hosted/pub.dartlang.org/widgetbook-2.4.1/lib/src/workbench/workbench_state.freezed.dart:415:31: Error: 'WidgetbookFrame' isn't a type.
          required final List<WidgetbookFrame> frames,
```

**Comment by naw2nd** [comment]
> I have the same problem with version 2.4.1, the only difference is that the Widgetbook.Frame class is missing
> 
> Maybe the reason is that the widgetbook_models in version 0.0.8 does not support this files?
> 
> ```
> pub-cache/hosted/pub.dartlang.org/widgetbook-2.4.1/lib/src/workbench/workbench_state.freezed.dart:415:31: Error: 'WidgetbookFrame' isn't a type.
>           required final List<WidgetbookFrame> frames,
> ```

I just face the same problem too.  I am new to this package, I followed exactly the same as the documentation, but I can't find the solution. Do I need to try the lower version or if there is anything else that I need to setup that is not mentioned in [widgetbook documentation](https://docs.widgetbook.io/widgetbook/setup)

`/C:/Users/-/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/widgetbook-2.4.1/lib/src/widgetbook.dart:99:10: Error: Type 'WidgetbookFrame' not found.
    List<WidgetbookFrame>? frames,`

**Comment by Knupper** [comment]
@jenshor  thank you for your reply, i have tested it and can verify that the problems are gone now. Thank you for the fast solution.

**Comment by jenshor** [comment]
Closing as this seems to be fixed.
