### ISSUE TITLE
Search bar unfocuses while use case is selected

### ISSUE THREAD

**Issue by mkucharski17** [widgetbook/widgetbook#424]
**Description**
The search bar unfocuses after typing a single character while a use case is currently selected. Without use case selection it works properly.

**Steps To Reproduce**

1. Go to any use case
2. Click on the search bar
3. Try to type three letters
4. Search bar unfocuses after the first.

**Expected Behavior**
Possibility to type may letter in a row.

**Screenshots**

https://user-images.githubusercontent.com/43498643/212560558-0a5d90ec-4622-4bf8-9956-bab5ca1f8756.mov

**Additional Context**
I tried only on the web using debug and release modes. The error does not depend on the mode.
I used widgetbook 2.4.1 .

**Comment by carloscasanovad** [comment]
Having the same problem here, any solutions or workarounds?

**Comment by jenshor** [comment]
We released a new beta version of Widgetbook that does not have this problem. We are quickly moving towards a stable release so stay tuned! 🚀 

Since this is already fixed in beta I'll close this issue. If you have additional feedback, let me know 👍🏻
