### ISSUE TITLE
Checkbox value is not reflected from widget to knobs and vice versa

### ISSUE THREAD

**Issue by marcotrumpet** [widgetbook/widgetbook#427]
**Description**
Adding a checkbox as usecase, you cannot tap on it to change status, you have to tap on knobs toggle.

**Steps To Reproduce**
Create a widgetbook app and add a WidgetbookUseCase
```dart
WidgetbookUseCase(
  name: 'checkbox',
  builder: (context) {

    return CheckboxListTile(
      value: context.knobs.boolean(
        label: 'test label',
        initialValue: false,
        description: 'this is a description',
      ),
      title: Text(
        context.knobs.text(
          label: 'label',
          initialValue: 'test label',
        ),
      ),
      onChanged: (value) {},
    );
  },
),
```
if you tap on checkbox nothing happens, if you use knob toggle it works
<img width="1196" alt="Screenshot 2023-01-18 at 09 18 26" src="https://user-images.githubusercontent.com/35219231/213119274-f176be26-22ef-4158-ac32-f351fd643b71.png">

**Expected Behavior**
Checkboxes should work with both knob toggle and by clicking on it.

**Additional Context**
A trick that kind of works is to change the code above using Provider and your KnobsNotifier
```dart
WidgetbookUseCase(
  name: 'checkbox',
  builder: (context) {
    final notifier = context.read<KnobsNotifier>();
    var checkboxValue = false;
    return CheckboxListTile(
      value: context.knobs.boolean(
        label: 'test label',
        initialValue: checkboxValue,
        description: 'this is a description',
      ),
      title: Text(
        context.knobs.text(
          label: 'label',
          initialValue: 'test label',
        ),
      ),
      onChanged: (value) {
        notifier.update('test label', value);
      },
    );
  },
),
```

In this way I'm able to trigger checkbox by tapping on it, but it doesn't reflect on knob toggle even if I use the update method with the notifyListener in it.

<img width="1194" alt="Screenshot 2023-01-18 at 09 23 05" src="https://user-images.githubusercontent.com/35219231/213120182-e9af48ff-f9ed-4e85-b35e-d76cf3166074.png">

**Comment by jenshor** [comment]
Thanks for raising this issue. I'll look into it for the Widgetbook 3 release 😊

**Comment by YoussefRaafatNasry** [comment]
The Knobs are unidirectional by default, which means editing the Knobs from the right side panel will update the Use-case, but NOT vice versa (i.e. updating the Use-case will NOT update the Knobs in the side panel).

On the other hand, there's a workaround if you still want bidirectional updates. You can use the following method to update a Knob manually in the `onChanged` of your widget:

```dart
CheckboxListTile(
  title: const Text('Title'),
  value: context.knobs.boolean(label: 'Checkbox Knob'),
  onChanged: (value) {
    WidgetbookState.of(context).updateKnobValue(
      'Checkbox Knob',
      value,
    );
  },
);
```

More info: [Discord Thread](https://discord.com/channels/879618555560218625/1143154260566098030)
