### ISSUE TITLE
Int Number Knob

### ISSUE THREAD

**Issue by jiwon79** [widgetbook/widgetbook#430]
I would like to suggest the following two things.

1. Add knob for integer
Currently, there is a knob that only input num type variable. Like html input number tag, I want a button that can increate the number by 1 with the arrow next to input box.

2. Add minium and maximun parameter for num knob
It would be nice if there are parameters that ignore value below the minimun value and above the maximun value.

**Comment by sur16-cse** [comment]
can i work on this issue

**Comment by Mastersam07** [comment]
Is this being worked on?

I am trying to code out some ideas for #17 but i could really use an IntField which i believe this PR would add?

**Comment by Mastersam07** [comment]
@YoussefRaafatNasry if this is not assigned, can i pick it up?

**Comment by MarkOSullivan94** [comment]
When will this be added to a release?

**Comment by YoussefRaafatNasry** [comment]
@MarkOSullivan94 The release will be ready early next week.
