### ISSUE TITLE
Why does `widgetbook_annotation` require production dependencies

### ISSUE THREAD

**Issue by ronnnnn** [widgetbook/widgetbook#436]
**Description**
I have a question about `widgetbook_annotation` dependencies.
I want to add dependencies (`widgetbook` `widgetbook_annotation` `widgetbook_generator`) to only `dev_dependencies` .
If I do it, [`depend_on_referenced_packages`](https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html) appear though I already added it.
I couldn't understand why this problem is happened.

If I add `widgetbook_annotation` to `dependencies` (production), the lint warning is not appear. So I want to know why `widgetbook_annotation` requires production dependencies.

**Steps To Reproduce**

1. add dependencies on pubspec.yml
```lml
dev_dependencies:
  widgetbook: ^2.4.1
  widgetbook_annotation: ^2.1.0
  widgetbook_generator: ^2.4.1
```

2. import `widgetbook_annotation` on some classes in `lib` dir.

**Screenshots**
<img width="1161" alt="スクリーンショット 2023-02-01 17 34 42" src="https://user-images.githubusercontent.com/12420269/215991578-841aa551-8fb9-47b5-968a-8c9f9a6ee01b.png">

**Comment by YoussefRaafatNasry** [comment]
This happens because you are trying to use a dependency inside a public directory (`lib`).
This is the same case with all other code generation packages (e.g. `freezed`, `json_serializable`, etc.), which makes it more of a Dart problem than a Widgetbook problem.
