### ISSUE TITLE
Make expanding and collapsing of Navigation Panel elements more accessible

### ISSUE THREAD

**Issue by JensHor** [widgetbook/widgetbook#44]
Collapsing and expanding Navigation Panel elements takes time for lange projects. especially if one wants to go through stories fast. 

## Suggested solution:

Include a button that makes expanding and collapsing the subtree of a navigation element easier.

**Comment by joshpetit** [comment]
So would the idea be to add a button that let's someone expand everything at once?

**Comment by JensHor** [comment]
@joshpetit Yes. I'd add a general button to expand everything similar to the approach mentioned in #62 but also add a button for each `Tile` (except `UseCase` tiles) to expand all its children.
