### ISSUE TITLE
fix(core): `NavigationBloc` does not handle encoded routes on `SelectNavigationNodeByPath` events

### ISSUE THREAD

**Issue by jenshor** [widgetbook/widgetbook#446]
**Description**
The `_onSelectNavigationNodeByPath` handler for `SelectNavigationNodeByPath` primarily handles routes that look like `package/component/use-case-1`. However, the implementation is used in a way in which it'll get routes that look like `/?path=package%2Fcomponent-2%2Fuse-case-2.1 ` which is not properly handled.

**Comment by YoussefRaafatNasry** [comment]
This bug no longer exist.
