### ISSUE TITLE
refactor(widgetbook): unnamed function type parameters

### ISSUE THREAD

**Issue by tenhobi** [widgetbook/widgetbook#457]
**Description**
In many places in the code, there are unnamed parameters in `Function` types. Especially around `Function(BuildContext)`, `Function(BuildContext, ...)`, `Function(T)`, ...

That works ok, but for the user, the IDE generates code like 

```dart
WidgetbookUseCase(
  name: 'test use case',
  builder: (p0) { // here, IDE generates (p0) {} instead of (context) {}
  },
),
```

as the reason that the type is defines as `Function(BuildContext)` and not `Function(BuildContext context)`.

Adding names of these parameters would further improve readability. 🙏 

// I would create a PR, but I am not sure what the proper name should be in many cases.

**Comment by jenshor** [comment]
Hey @tenhobi, thanks for raising this issue. Makes sense to me. Fixing this might take some time since it's not highest priority right now but we'll look into it 👍🏻
