### ISSUE TITLE
Zoom Addon

### ISSUE THREAD

**Issue by Rohithgilla12** [widgetbook/widgetbook#512]
**Description**

Previously there was a zoom button

![image](https://user-images.githubusercontent.com/19389850/219650958-6c83ee1b-6024-40e0-8e5a-12bd33b2fa9c.png)

In the current pre-release version it's missing.

![image](https://user-images.githubusercontent.com/19389850/219650094-4e7508ed-68de-45b0-bac9-efd1e1a61a83.png)

**Steps To Reproduce**

1. Go to the example applicaiton

**Expected Behavior**
![image](https://user-images.githubusercontent.com/19389850/219650958-6c83ee1b-6024-40e0-8e5a-12bd33b2fa9c.png)

In the current pre-release version it's missing.

![image](https://user-images.githubusercontent.com/19389850/219650094-4e7508ed-68de-45b0-bac9-efd1e1a61a83.png)

**Comment by jenshor** [comment]
Hey, thanks for raising this issue. We intentionally removed the zoom feature as it was a bit clunky and hard to use. However, we aim to re-add the feature when we find a way to make it accessible for Widgetbook users. 
Any ideas on how to do so are welcome 😊

**Comment by Rohithgilla12** [comment]
@jenshor Sure, we can have an `addon` for zoom.

I will try to make a PR if possible 😄

**Comment by jenshor** [comment]
@Rohithgilla12 sounds good.

However, I'm not sure yet if we should implement zoom on a `FrameAddon` level or create a new `ZoomAddon`. 
You can have a look into the Addon API first and we can talk about implementation details later 👍🏻

**Comment by jenshor** [comment]
The zoom should meet the #531 requirement.

**Comment by Rohithgilla12** [comment]
Yes 💯 
Sure, would check the `Addon API` thanks!

**Comment by Mastersam07** [comment]
@YoussefRaafatNasry can this be assigned to me?

**Comment by Mastersam07** [comment]
@YoussefRaafatNasry is it possible i can get a reference to a widgetbook version that has Zoom controls?

I checked against `widgetbook-widgetbook-v3.3.0` but wasn't sure Zoom controls were still there.

I have a solution but want to check against the old zoom feature which @jenshor mentioned to be clunky and hard to use.

**Comment by YoussefRaafatNasry** [comment]
@Mastersam07 I have found this really old code [here](https://github.com/widgetbook/widgetbook/blob/38b0f7a07a6167d8ea3784bfbe3daed621d3d06a/lib/widgets/story_render.dart#L53-L69) from Widgetbook 2 I guess _(even before I've joined the team)_. Hope it can be a little bit helpful.
