### ISSUE TITLE
no way to use widgets that require localization

### ISSUE THREAD

**Issue by maks** [widgetbook/widgetbook#53]
I have widgets that make use of Flutters standard localisation mechanism and so require having `localizationsDelegates` and `supportedLocales` set on their containing `MaterialApp` but there is currently no way to do so for the `MaterialApp` widget that widgetbook uses internally.

**Comment by JensHor** [comment]
Yes, this is currently not implemented. We'll keep you posted on this issue 👍🏻

**Comment by maks** [comment]
Thanks @JensHor 👍🏻 , I'll keep an eye out, as currently this is a blocker for me to try using Widgetbook.

**Comment by edTheGuy00** [comment]
I simply created a `MaterilaApp` wrapper widget like:

```dart
class TranslationsWrapper extends StatelessWidget {
  final Widget child;
  final String lang;

  const TranslationsWrapper({Key? key, required this.child, required this.lang})
      : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [
        Translations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      locale: Locale(lang),
      supportedLocales: Translations.delegate.supportedLocales,
      home: child,
    );
  }
}
```

Which lets me create language specific usecases like:

```dart
 useCases: [
          WidgetbookUseCase(
            name: "Main - EN",
            builder: (ctx) {
              return TranslationsWrapper(
                child: OnBoardingScreen(),
                lang: 'en',
              );
            },
          ),
          WidgetbookUseCase(
            name: "Main - JP",
            builder: (ctx) {
              return TranslationsWrapper(
                child: OnBoardingScreen(),
                lang: 'ja',
              );
            },
          )
        ],
```

**Comment by maks** [comment]
Thanks @edTheGuy00 I could have sworn I tried wrapping in a MaterialApp initially when I ran into it without sucess, but I just tried again and it does work fine! Though it would be nice to have this fixed in widgetbook so that we dont end up with nested MaterialApp widgets.

**Comment by edTheGuy00** [comment]
@maks I agree. I think the best approach would be to provide the localizations to the `WidgetBook` class and show a language selection on the WidgetBook app bar that allows the user to change their languages. Much better than creating separate UseCases for languages like I did.

**Comment by JensHor** [comment]
@edTheGuy00 that is indeed how we plan to implement this feature, but it will probably take a while since we are currently working on other features. We'll keep you posted on the progress 👍🏻

**Comment by Butzlabben** [comment]
Any ETA on this issue? Or is maybe a PR welcome?

**Comment by JensHor** [comment]
@Butzlabben we currently have no ETA on this feature but a PR is always welcome 💙 If you are planning to work on this please be aware of our [CLA](https://docs.google.com/forms/d/e/1FAIpQLScuRfjUzENsLsmQgqZlGLxMKbFi7zuXoPARyXytoyQrq7ntUw/viewform)

**Comment by JensHor** [comment]
ETA just moved up to next week 🚀

**Comment by JensHor** [comment]
We just fixed this (and many other issues) as a beta release on [pub.dev](https://pub.dev/packages/widgetbook/versions/2.0.2-beta). We are still adjusting the generator to the breaking changes, but the updated generator will likely land next week. Let us know what you think!

**Comment by tieorange** [comment]
Guys is there any updates on this? 

How do I make it work with localizations?

**Comment by jenshor** [comment]
@tieorange have a look at our [documentation regarding localization](https://docs.widgetbook.io/widgetbook/properties#localization). If you have issues, let us know within a new issue or via discord.

**Comment by tieorange** [comment]
Line #17 fixed an issue for me.
<img width="601" alt="image" src="https://user-images.githubusercontent.com/3984517/181064490-87e7825f-b8e3-4e4b-ac19-d3d6e85ee389.png">


@jenshor  I guess it will be great to add it to docs here above this line: 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/3984517/181064699-18712e13-14a6-4111-bcae-c31c47a7aef9.png">
