### ISSUE TITLE
docs: outdated custom `Device` parameters naming

### ISSUE THREAD

**Issue by lore-co** [widgetbook/widgetbook#539]
In the documentation it appears the custom Device properties are not correctly named.

https://docs.widgetbook.io/widgetbook/properties#define-your-own-device

For example "width" and "height" have been renamed as "nativeWidth" and "nativeHeight".

**Comment by jenshor** [comment]
Hey @lore-co, thanks for raising this issue. We'll adjust the docs 👍🏻

**Comment by YoussefRaafatNasry** [comment]
`Device` was removed in #665, we now use `DeviceInfo` from `device_frame` directly.
