### ISSUE TITLE
fix(generator): bump `analyzer` version to most recent 

### ISSUE THREAD

**Issue by jenshor** [widgetbook/widgetbook#543]
**Description**
`widgetbook_genrator` is not using the most recent version of the `analyzer` dependency causing developers problems using the generator. 

**Additional Context**
[Inform discord user once the issue has been resolved](https://discord.com/channels/879618555560218625/879697921749184572/1082956946530898002)

**Comment by stou** [comment]
+1 This issue prevents using widgetbook with realm, since realm_generator has a dependency on analyzer: ^5.0.0
