### ISSUE TITLE
feat: add expand and collapse for use-case tile

### ISSUE THREAD

**Issue by LucasJosefiak** [widgetbook/widgetbook#558]
**Description**
The use-case tile currently only shows three dots without functionality in the right corner which suggest that they are clickable and open settings etc.

Instead, we should add the following functionality:
- collapse all: collapses the directory as well as all sub directories
- expand all: expands the directory as well as all sub directories

**Steps To Reproduce**

1. Open a Widgetbook
2. Click and hover over a UseCase
3. See the three dots in the right corner

**Screenshots**
<img width="309" alt="Screenshot 2023-03-17 at 17 44 01" src="https://user-images.githubusercontent.com/69841305/225968461-281cdb70-598c-4800-bfcb-17e90ccf1ea7.png">

**Comment by YoussefRaafatNasry** [comment]
The 3 dots button has been removed in previous versions.
