### ISSUE TITLE
fix(widgetbook): default theme property is not set in `DropdownMenu`

### ISSUE THREAD

**Issue by LucasJosefiak** [widgetbook/widgetbook#560]
**Description**
When running Widgetbook on the web, the theme property is not set initially in the UI. It should show the theme that is selected by default.

**Steps To Reproduce**

1. Go to Widgetbook Cloud
2. Click on one of our test projects
3. Click on the latest branch and build
4. Click on one of the WidgetbookComponents, e.g. AuthButton
5. See that no theme is shown in the theme property in the property panel on right side

**Expected Behavior**
It should show the theme that is selected by default.

**Screenshots**
<img width="225" alt="Screenshot 2023-03-20 at 14 21 58" src="https://user-images.githubusercontent.com/69841305/226353545-b0377d81-b095-442f-8a58-74d2026ee59d.png">
<img width="1833" alt="Screenshot 2023-03-20 at 14 21 54" src="https://user-images.githubusercontent.com/69841305/226353553-609c0b14-866f-4624-93aa-fef8882ed2f2.png">

**Additional Context**
I noticed the problem myself in demo calls.

**Comment by jenshor** [comment]
Just checked the code. Works for manual widgetbook, but I was able to reproduce the problem for widgetbook_generator. 

With the generator, a method is called returning a `Theme`. For some reason, `ThemeData` does not seem to be equatable, so it's hard to compare to objects that have been created with the same constructor parameters. 

<img width="484" alt="image" src="https://user-images.githubusercontent.com/16862002/226386578-8ba09e50-d459-4624-a809-66eccbe42901.png">
In the image, we see that `getLightTheme` gets called twice, causing the problem. A better approach would pass the same object into the `activeTheme` and the `themes` array.
