### ISSUE TITLE
feat: read only widget properties

### ISSUE THREAD

**Issue by lore-co** [widgetbook/widgetbook#563]
It would very useful to be able to set read-only widget properties in order for eventual testers and design teams to check whether the widget they are using has the the expected properties set.

Sure, the implementing dev could add them in the same screen as a plain Text Widget, but it would be a nice QoL to be able to set them like knobs, on the right of the widgetbook UI

**Comment by jenshor** [comment]
Hey @lore-co, thanks for opening another feature request 😊 

I'm not sure if I understand this request properly. Do you mean read-only knobs? 
You maybe show some code how it might work in Widgetbook and describe what the Widgetbook UI looks like?

**Comment by MarcusHolanda1** [comment]
Hey @jenshor, I think what he meant was exactly what I'm showing in the print below, it would be a kind of documentation of the component's properties.
![image](https://user-images.githubusercontent.com/77813543/232093791-978f338b-ee28-4b40-b2ce-18b9b7cc10d1.png)

**Comment by YoussefRaafatNasry** [comment]
Closing this in favor of #70.
The documentation feature should have a list of the properties of the Widget.

**Comment by Rasha-Mosaed** [comment]
how can we use this feature ?

**Comment by LucasJosefiak** [comment]
As mentioned in the comment above, unfortunately, you have to wait for this feature to be released: https://github.com/widgetbook/widgetbook/issues/70

Please let us know if you'd like to support us during the development of the feature.
