### ISSUE TITLE
feat: [QoL] custom widget knobs labels

### ISSUE THREAD

**Issue by lore-co** [widgetbook/widgetbook#564]
As title says it would be great if we could set a custom widget for Knobs labels.

Let says we want to have a knob with a very long list of Icon options and want the tester/designers to easily see what icon each option provides without having to try every one of them.
It would be easier for them to see a preview of the icon as a leading/trailing widget along with its label, won't you think?

**Comment by jenshor** [comment]
Thanks for opening this feature request 👍🏻

We'd like to open up and improve the API for implementing your own custom knobs. In addition, it likely makes sense to have an icon knob that allows for selecting, previewing, and searching (if possible) for icons.

However, I'm not sure if having a custom label of type `Widget` would be beneficial. 
These questions come to my mind that block the implementation of such a feature:
- How can we maintain a consistent design for Widgetbook if devs can use custom Widget-based labels?
- The knob implementation requires a unique identifier. This is currently the `label`. We could also make it a Widget, but if it changes based on values it will cause problems. 
- Is it sufficient to have the preview as part of the content of a knob? Why do we need previews in the label?

Happy to discuss the options and additional ideas 😊

**Comment by lore-co** [comment]
> Thanks for opening this feature request 👍🏻
> 
> We'd like to open up and improve the API for implementing your own custom knobs. In addition, it likely makes sense to have an icon knob that allows for selecting, previewing, and searching (if possible) for icons.
> 
> However, I'm not sure if having a custom label of type `Widget` would be beneficial. These questions come to my mind that block the implementation of such a feature:
> 
> * How can we maintain a consistent design for Widgetbook if devs can use custom Widget-based labels?
> * The knob implementation requires a unique identifier. This is currently the `label`. We could also make it a Widget, but if it changes based on values it will cause problems.
> * Is it sufficient to have the preview as part of the content of a knob? Why do we need previews in the label?
> 
> Happy to discuss the options and additional ideas 😊

I'll try in answering point by point to your questions

1- This is a rightful concern and the most obvious drawback it comes to mind when thinking about custom widgets.
  But what about if we reduced the possibilities and give the option to display a preset widget (made and chosen by you) 
  containing limited information?
  
  But yeah, this is a clear issue that needs to be approached carefully as I guess you don't want users to create custom knobs widgets covering like 3/4 of the screen 😄 

3- The idea is to make easier to associate knobs options to what they "contains".
   Let's suppose we have a list of Material Icons and we want our widget to change icon based on what we pass in its constructor.

We would probably pass the icon list to our knob's options, using their material name or their code as a label.
While we'd probably have an easier time browsing a short list of icons before picking one, with a very big list, testers would have to navigate the list based only on the icon code or name, while associating it with an icon preview would make the work easier.

It's not really a ground-breaking feature, and something I believe would not worth if you'd have tom break apart the whole widget book source code, just an eventually nice QoL

**Comment by kekland** [comment]
@lore-co @jenshor I think this is a great thing to have. Currently I've had to create a custom knob for this, but the end-result looks pretty nice:

![image](https://user-images.githubusercontent.com/14993994/230724569-9de9aae9-421f-46ef-9d41-9f937bee69d8.png)
![image](https://user-images.githubusercontent.com/14993994/230724576-59591ccd-6f28-4858-83a7-e19c1cdea082.png)

I think what can be done here is:

- Keep the `context.knobs.options` as it is to avoid making breaking changes and allowing it to be used for simple cases

- Add a `context.knobs.customOptions` method, which allows the user to return a `DropdownMenuEntry` from the `labelBuilder` method. This way, the `label` is still obtainable from the entry for the knob to work; and the `leadingIcon` and `trailingIcon` values can be supplied to the entry to display some extra information about the option.

**Comment by YoussefRaafatNasry** [comment]
@lore-co The knobs are now based on the [Fields System](https://docs.widgetbook.io/field-types) which allows knobs to be rendered in Widgetbook Cloud (as it's built in React and not Flutter).

The good news is that you can still create [custom knobs](https://docs.widgetbook.io/knobs/custom-knob), but you have to be using one of the pre-defined fields. You can also submit an issue if you think we can add more fields to serve your needs.
