### ISSUE TITLE
refactor: knobs

### ISSUE THREAD

**Issue by jenshor** [widgetbook/widgetbook#565]
## Description
Developers using Widgetbook love the knobs. Due to additional feature required that piled up, we are now considering to refactor the knob implementation.
This issue serves as an overview of how the API needs to be refactored to support the needs of the community. 

## Related issues
- #583
- #564 
- #557 
- #538 
- #483 
- #430
- #427 
- #400
- #368 
- #227 and #228 
- #205 
- #188 

## General todos
- Icon Knob
- DateTime knob
- Generator support

**Comment by YoussefRaafatNasry** [comment]
I will be closing this for less clutter, _since most sub-issues are closed,_ and track the open issues individually.
