### ISSUE TITLE
KnobsBuilder should be exported

### ISSUE THREAD

**Issue by Albert221** [widgetbook/widgetbook#583]
Hi!

There are sometimes cases where I have a list of values (like an enum) that my widgets accept. I'd like to create an extension method on `KnobsBuilder` for this type, that uses `options()` inside, but currently I need to import the `package:widgetbook/src/knobs/knobs_builder.dart` which is not ideal and it breaks `implementation_imports` lint.

I'm proposing exporting the `KnobsBuilder` from the `widgetbook` library, so that we'll be able to create custom knobs without a problem :)

Example use-case:

```dart
// ignore: implementation_imports
import 'package:widgetbook/src/knobs/knobs_builder.dart';
import 'package:widgetbook/widgetbook.dart';

extension FooIconKnobsBuilderExtension on KnobsBuilder {
  FooIcon? nullableFooIcon({required String label}) {
    return options(
      label: label,
      options: [
        const Option(
          label: 'null',
          value: null,
        ),
        for (final icon in FooIcons.values)
          Option(label: icon.name, value: icon),
      ],
    );
  }
}
```

And then in my `WidgetbookUseCase` I can simply use `icon: context.knobs.nullableFooIcon(label: 'Icon')`

**Comment by YoussefRaafatNasry** [comment]
`KnobsBuilder` was [exported](https://github.com/widgetbook/widgetbook/pull/682/files#diff-776266f4a3254035efb59efe98407d1c8e923b721d6b1efd321b6539adc80a77) in #682
