### ISSUE TITLE
How to use within a package or plugin?

### ISSUE THREAD

**Issue by eggnstone** [widgetbook/widgetbook#59]
Please document how to use widgetbook with a Flutter package or plugin; or document that this is not possible.

Use case: I am developing and maintaining a public package which would benefit from having an accompanying widgetbook.

Current problem: 
```
flutter create --platforms=windows .
The "--platforms" argument is not supported in package template.
```

**Comment by JensHor** [comment]
Using Widgetbook within a package is difficult. As a workaround, we recommend to create another flutter app which is used to launch the Widgetbook. The package which should be injected into Widgetbook is then added as a dependency to the project. 

The workaround has a few drawbacks. 

Do you have any suggestions how we can improve this?

**Comment by eggnstone** [comment]
I thought of the same solution but had hoped you would have a better way.

I guess adding the widgetbook app inside the package (the same way the auto-generated example is) would be the best way.
