### ISSUE TITLE
How to set a default theme?

### ISSUE THREAD

**Issue by eggnstone** [widgetbook/widgetbook#60]
I want to use the light theme as the startup theme. How to achieve that?

**Comment by JensHor** [comment]
Currently that's not possible. For now, you can switch the theme in the UI to the light theme as a workaround.

**Comment by JensHor** [comment]
We just fixed this (and many other issues) as a beta release on [pub.dev](https://pub.dev/packages/widgetbook/versions/2.0.2-beta). We are still adjusting the generator to the breaking changes, but the updated generator will likely land next week. 

The default theme is always the one that is defined first in `themes`. Let us know if that works for you!
