### ISSUE TITLE
Add-on proposal: `TimeDilationAddon`

### ISSUE THREAD

**Issue by kekland** [widgetbook/widgetbook#613]
**Description**
I often use Widgetbook to build and then test out widgets and entire pages. However, sometimes testing out animations is a bit tricky - especially if they're very fast. To solve this issue, I've created a `TimeDilationAddon` in my own project.

This works by adjusting the `timeDilation` property in the Flutter's scheduler, which will slow down the ticker by the amount set in the property. For example, setting `timeDilation = 2.0` will slow everything down by a factor of 2.

https://user-images.githubusercontent.com/14993994/230728560-a2ba71cf-dd67-42eb-9980-3e2eb592159b.mp4

One drawback of this method is that this will slow down **everything** - including Widgetbook's animations themselves (i.e. stuff like dropdown buttons for knobs will open very slowly).

If this sounds interesting, I can open a pull request with this addon.

**Comment by YoussefRaafatNasry** [comment]
Hello @kekland 👋 
Apology for the late response, we have been busy moving Widgetbook 3 from beta to stable.

This addon idea sounds interesting!
Would you like to work on it?

**Comment by kekland** [comment]
Hi @YoussefRaafatNasry!

Currently I'm very busy with some of my other projects, so I can't really dedicate time to check if there's been any additions or updates to Widgetbook and to migrate the addon. 

Here's the addon's code that we're using for our Widgetbook:

```dart
import 'package:watchcrunch/widgetbook.dart';
import 'package:widgetbook_core/widgetbook_core.dart';
import 'package:flutter/scheduler.dart' as scheduler;

class TimeDilationModel extends WidgetbookAddOnModel {
  TimeDilationModel({required this.timeDilation});

  final double timeDilation;

  @override
  Map<String, String> toQueryParameter() {
    return {'time-dilation': timeDilation.toString()};
  }
}

class TimeDilationAddon extends WidgetbookAddOn<TimeDilationModel> {
  TimeDilationAddon({
    required super.setting,
  }) : super(name: 'time-dilation');

  final options = [0.25, 0.5, 1.0, 2.0, 4.0, 8.0, 16.0];

  @override
  Widget build(BuildContext context) {
    final timeDilation = value.timeDilation;
    scheduler.timeDilation = timeDilation;

    return Setting(
      name: 'Time dilation',
      child: DropdownSetting<double>(
        options: options,
        initialSelection: timeDilation,
        optionValueBuilder: (timeDilation) => timeDilation.toStringAsFixed(2),
        onSelected: (newTimeDilation) {
          onChanged(
            context,
            TimeDilationModel(timeDilation: newTimeDilation),
          );
        },
      ),
    );
  }

  @override
  TimeDilationModel settingFromQueryParameters({
    required Map<String, String> queryParameters,
    required TimeDilationModel setting,
  }) {
    if (queryParameters['time-dilation'] != null) {
      return TimeDilationModel(
        timeDilation: double.parse(queryParameters['time-dilation']!),
      );
    }

    return setting;
  }
}
```

Feel free to integrate it into Widgetbook (if that's planned)

**Comment by YoussefRaafatNasry** [comment]
Thanks @kekland!
We will take it from here.
