### ISSUE TITLE
Feature request: Sort widgets (and stories) alphabetically 

### ISSUE THREAD

**Issue by eggnstone** [widgetbook/widgetbook#62]
Currently the list of widgets is random.

**Comment by JensHor** [comment]
are you using the `widgetbook` package or the `widgetbook_generator` package?

**Comment by JensHor** [comment]
We will likely implement a button with which the user can specify how to sort the navigation panel elements 

Options:
- Ascending
- Descending 

Folders will probably always show on top of widgets regardless of their naming.

**Comment by eggnstone** [comment]
> are you using the `widgetbook` package or the `widgetbook_generator` package?

Both, but the widgetbook app is generated by the generator. I think that's what you are asking.

**Comment by eggnstone** [comment]
> We will likely implement a button with which the user can specify how to sort the navigation panel elements
> * Ascending
> * Descending

I personally don't see a use case to sort alphabetically descending but as long as alphabetically ascending is available (and the default) I'll be happy :)

**Comment by joshpetit** [comment]
I could see that people would very well want to have things in a specific order, for example to have to use cases next to each other. I would suggest we add a button that defaults to unsorted but can be toggled to sort alphabetically everywhere.

**Comment by JensHor** [comment]
@joshpetit yes that would be great. I think the button could be placed between the `SearchBar` and the first shown category widget to create a `ButtonBar` for such settings 👍🏻

**Comment by YoussefRaafatNasry** [comment]
Good news, @eggnstone 🎉 
This will be available in our next `widgetbook_generator` release, stay tuned!

Apology it took longer than it should. We were busy doing **proper** refactoring to the `widgetbook_generator` package, to be able to do a _simple_ fix for this.
