### ISSUE TITLE
Proposal: resizable side panels

### ISSUE THREAD

**Issue by kekland** [widgetbook/widgetbook#621]
**Description**
I wonder if making the side panels resizable (or at least providing some ability to change their size) is possible? Currently, if the components have some long names (or are deeply nested) then the text is overflown.

**Comment by LucasJosefiak** [comment]
Another user just mentioned this issue too

<img width="1440" alt="Screenshot 2023-04-25 at 21 40 37" src="https://user-images.githubusercontent.com/69841305/235671345-ebdcb5ca-19f1-4433-90ad-2ececcf69297.png">

**Comment by vHanda** [comment]
With WidgetBook2, I could at least horizontally. Now with version 3, it's impossible to figure out the names.

**Comment by Kiruel** [comment]
<img width="294" alt="Screenshot 2023-06-07 at 15 09 23" src="https://github.com/widgetbook/widgetbook/assets/8250175/78b99771-0cfc-41de-a35b-81663015328e">


Another example, it's impossible to read the name of the widget.
