### ISSUE TITLE
Please expand the documentation to explain categories, folders, and stories.

### ISSUE THREAD

**Issue by eggnstone** [widgetbook/widgetbook#64]
- I see that one can create `categories`, but can they be nested? And how?
- What is a `Folder` and how is it different from a `Category`?
- Why is `stories` holding a list of use cases. Shouldn't the container then be called `useCases` or the item `Story`?

**Comment by JensHor** [comment]
Categories cannot be nested. 

Do you think Categories is necessary at all? It could also be replaced by folder.

**Comment by JensHor** [comment]
Which version of widgetbook are you using? 

We renamed the `stories` properties to `useCases` in `widgetbook: 1.0.1`

**Comment by eggnstone** [comment]
>Do you think Categories is necessary at all? It could also be replaced by folder.
Well, as I don't understand the difference yet nor the reason for its existence I cannot competently comment on that. But yeah, that's what I thought :)

>Which version of widgetbook are you using?
I was reading the current documentation on https://pub.dev/packages/widgetbook.
