### ISSUE TITLE
I can't access to the images in my widgets

### ISSUE THREAD

**Issue by danieltaveragb** [widgetbook/widgetbook#647]
**Description**
When I try to use the next path: `assets/images/whatever.png` will not work unless if I use `images/whatever.png`
It's like widgetbook is adding `assets/assets/images/whatever.png` another `assets`.

How can I remove that behavior from widgetbook? I can not send the path without the assets because It's part of a package that already works

**Comment by YoussefRaafatNasry** [comment]
@danieltaveragb This seems like a weird behavior. Please send a minimal reproduction repo to help us investigate it more.
Closing this for now until the reproduction repo is ready.
