### ISSUE TITLE
Components are shown in the top left corner instead of in the center

### ISSUE THREAD

**Issue by LucasJosefiak** [widgetbook/widgetbook#654]
**Description**
One user described that he wants to show his components, e.g. an `ElevatedButton`, in the center. However, it's shown in the top left corner. 

**Steps To Reproduce**

1. Go to our demo app
2. Run Widgetbook
3. Search for Elevated Button
4. Open a use case
5. See the button in the top left corner and not in the center

**Expected Behavior**
See the button in the center

**Screenshots**
![Screenshot 2023-04-27 at 16 24 18](https://user-images.githubusercontent.com/69841305/234892406-b74d83ac-b392-4d70-bba0-03973819befb.png)

**Comment by YoussefRaafatNasry** [comment]
@LucasJosefiak I think leaving the top-start alignment as the default behavior is reasoanble for testing widgets that depend on the parent layout.
To solve this issue tho, we can introduce and Alignment Addon that users can use to change where there use case is displayed.

cc @jenshor

**Comment by LucasJosefiak** [comment]
@YoussefRaafatNasry I like the idea! Looking forward to seeing it in action!😎
