### ISSUE TITLE
Dropdown for option knob enums

### ISSUE THREAD

**Issue by LucasJosefiak** [widgetbook/widgetbook#660]
**Description**
There is a UX issue with the option knob. For enums, in the dropdown, it shows the name of the enum plus the value. However, users only want to see the value.

**Comment by jenshor** [comment]
For formatting on how a knob option is shown users can use the `labelBuilder` property.

**Comment by wwwdata** [comment]
Is there currently a bug with `labelBuilder`? When I use it, it correctly displays my labels, however when I pick one of the options the value passed to my widget is always `null` which breaks the full functionality :D Everything works fine when I am not using `labelBuilder`. Widgetbook version `3.5.0`
