### ISSUE TITLE
flutter widgetbook : Install and use widgetbook as a package has problem

### ISSUE THREAD

**Issue by tazik561** [widgetbook/widgetbook#668]
I am trying to use widgetbook in my project, but I don't want to make it inside my project. I want to use it like a package. because I want to use for a few projects and these projects use the same widgets. It is not good practice to add widgethook inside projects one by one, instead, I want to use it as a package and this package is common between all projects.  So I created a package and inside my package, I created an example Project:

    MyPackage
    ├─ lib
    │  ├─ main.dart
    ├─ Example
    │  ├─ lib
    │  ├──| main.dart
    │  │──pubspec.yaml
    ├─ pubspec.yaml

Inside package pubspec.yaml I added these libs:

    dependencies:
      flutter:
        sdk: flutter
      widgetbook_annotation:
    
    dev_dependencies:
      flutter_test:
        sdk: flutter
      flutter_lints: ^2.0.0
      widgetbook:
      build_runner:
      widgetbook_generator:

and Inside Example pubspec.yaml I added these libs:

    dependencies:
      flutter:
        sdk: flutter
      cupertino_icons: ^1.0.2
    
      eazy_widgetbook: --> my package
        path: ../
    
    dev_dependencies:
      flutter_test:
        sdk: flutter
      build_runner:

and In package main dart I exported :

    library eazy_widgetbook;
    
    export 'package:widgetbook_annotation/widgetbook_annotation.dart';

Now In example project in main dart I wrote these commands: 

    void main() {
      runApp(const MyApp());
    }
    
    @WidgetbookApp.material(
      name: 'Meal App',
      frames: const [
        WidgetbookFrame(
          name: 'Widgetbook',
          allowsDevices: true,
        ),
        WidgetbookFrame(
          name: 'None',
          allowsDevices: false,
        ),
      ],
      devices: [Apple.iPhone12],
      textScaleFactors: [
        1,
        2,
        3,
      ],
      foldersExpanded: true,
      widgetsExpanded: true,
    )
    class MyApp extends StatelessWidget {
      const MyApp({super.key});
    
      // This widget is the root of your application.
      @override
      Widget build(BuildContext context) {
        return const MaterialApp();
    
      }
    }
 But I got :

`Undefined name 'WidgetbookApp' used as an annotation. (Documentation)  Try defining the name or importing it from another library.``

[![enter image description here][1]][1]

there is not good example for [widgetbook][2] and there is no good document for it unfortunately. 

  [1]: https://i.stack.imgur.com/D0B0a.png
  [2]: https://docs.widgetbook.io/widgetbook-annotation/annotations

**Comment by YoussefRaafatNasry** [comment]
@tazik561 This is an unusual setup, please provide a reproduction repo to be able to investigate this issue more.
Closing this until a reproduction repo is provided, feel free to re-open again.
