### ISSUE TITLE
Flutter support closed?

### ISSUE THREAD

**Issue by samatzhusup** [widgetbook/widgetbook#719]
Hi there!

Support for [flutter](https://pub.dev/packages/widgetbook) closed?

I see the last update was 11 months ago

**Comment by devfelipereis** [comment]
They just released 3.0 RC1.

https://github.com/widgetbook/widgetbook/issues/672#issuecomment-1574840230

**Comment by YoussefRaafatNasry** [comment]
As @devfelipereis, we have released the [3.0.0-rc.1](https://pub.dev/packages/widgetbook/versions/3.0.0-rc.1), and it will go to the stable channel in 3-4 weeks.
