### ISSUE TITLE
problem with Widgetbook running in chrome

### ISSUE THREAD

**Issue by dileep9490** [widgetbook/widgetbook#722]
**Description**
I've added the following dependencies in pubspec.yaml 
```
  widgetbook_annotation: ^2.1.0

  widgetbook: ^2.4.1
  widgetbook_generator: ^2.4.1
```
and added the following code on top of my DemoHomePage widget

```
@WidgetbookApp.material(
  name: "DemoHomePage",
  devices: [
    Apple.iPhone11,
    Samsung.s21ultra,
  ],
)
```
this is the Error i'm getting

![image](https://github.com/widgetbook/widgetbook/assets/63330310/e74dccbe-fb19-47aa-97cd-ecbd9dae21d1)

**Comment by YoussefRaafatNasry** [comment]
Widgetbook v2 is **no longer supported**, please use our latest [3.0.0-rc.1](https://pub.dev/packages/widgetbook/versions/3.0.0-rc.1).

**Comment by dileep9490** [comment]
I'm getting the following error I just updated the widgetbook to 3

![image](https://github.com/widgetbook/widgetbook/assets/63330310/d81aba92-4b2b-45fe-9c5e-2025473f69e9)
