### ISSUE TITLE
Widgetbook as dev dependency

### ISSUE THREAD

**Issue by LucasJosefiak** [widgetbook/widgetbook#73]
One user wished that Widgetbook should be a dev dependency and not a dependency.

**Comment by mvolpato** [comment]
![Screenshot 2021-12-04 at 11 13 50](https://user-images.githubusercontent.com/7138011/144705765-c09c1b20-2173-4abb-aba9-802afafdc596.png)

Isn't it the case already?

**Comment by JensHor** [comment]
Yes, in the video it is described correctly. However in the documentation (especially [package:widgetbook_generator](https://pub.dev/packages/widgetbook_generator)) the dependency to widgetbook is listed as a (production or non dev) dependency.

**Comment by mvolpato** [comment]
I can address this and  submit a PR, if you guys don't mind.

**Comment by JensHor** [comment]
It would be amazing if you could submit a PR. But we are currently working on a Contributor License Agreement (CLA) which will be a requirement for any PR.

**Comment by mvolpato** [comment]
I will wait then :)

**Comment by JensHor** [comment]
I just created a template for PRs in which the [CLA](https://docs.google.com/forms/d/e/1FAIpQLScuRfjUzENsLsmQgqZlGLxMKbFi7zuXoPARyXytoyQrq7ntUw/viewform) can be found.

**Comment by mvolpato** [comment]
![Screen Shot 2021-12-17 at 16 09 51](https://user-images.githubusercontent.com/7138011/146565352-75e6aa7d-ed7e-4c05-86b2-a0c2073e0a7e.png)

**Comment by JensHor** [comment]
The CLA should be accessible now.
