### ISSUE TITLE
Wrapping all use cases in other widgets

### ISSUE THREAD

**Issue by LucasJosefiak** [widgetbook/widgetbook#74]
Feedback of one user: "My early feedback is to add some means of wrapping all use cases in other widgets. I have a kind of my own Theme, I'm not using the Material one, and right now I have to wrap every widget inside the usecase with that. Something like a Widget builder (Widget usecase) for a Widgetbook (or maybe even the categories/folders for scoping) would be really handy"

**Comment by prolificcoder** [comment]
👍  on this. We have our own theme and not able to load it in anywhere in the Widgetbook class. 

For some inspiration take a look at https://github.com/eBay/flutter_glove_box/blob/3b82f4e1b86cc2351f599f743815afc0500df4e8/packages/golden_toolkit/lib/src/testing_tools.dart#L95

this what we are using to load our custom stuff in widget tests.

**Comment by JensHor** [comment]
We just fixed this (and many other issues) as a beta release on [pub.dev](https://pub.dev/packages/widgetbook/versions/2.0.2-beta). We are still adjusting the generator to the breaking changes, but the updated generator will likely land next week. Let us know what you think!
