### ISSUE TITLE
Show/Hide Side Panels

### ISSUE THREAD

**Issue by mjablecnik** [widgetbook/widgetbook#748]
Can you add buttons for show/hide left and right panels?

**Comment by Mujhtech** [comment]
@YoussefRaafatNasry I would like to work on this issue

**Comment by vaishnavi-2307** [comment]
@YoussefRaafatNasry  can you please assign this issue to me, i would love to work on this issue and learn from it.

**Comment by Anurag-space** [comment]
@YoussefRaafatNasry 
i would like to work to this issue.Could you please assign me this issue.

**Comment by YoussefRaafatNasry** [comment]
Duplicate of #805
