### ISSUE TITLE
Issue with generating Widgetbook directories file when using test files

### ISSUE THREAD

**Issue by Bassiuz** [widgetbook/widgetbook#780]
I'm encountering an issue when trying to use Widgetbook in my Flutter app with test files. I want to define the use cases for Widgetbook in a test file so that I can also utilize them as input for my tests. However, when the buildrunner runs, it generates the widgetbook.directories.g.dart file, which imports the classes from the lib folders as assets instead of the actual widgets. As a result, the directories file cannot find the actual widgets and, consequently, cannot include them in the Widgetbook.

**Reproduction Steps:**

Clone the example repository: https://github.com/Bassiuz/widgetbook_test_setup
Run the buildrunner to generate the widgetbook.directories.g.dart file.
Observe that the directories file imports the classes from the lib folders as assets, instead of the actual widgets.
Expected Behavior:

I expect the buildrunner to generate the widgetbook.directories.g.dart file correctly, importing the actual widget classes rather than treating them as assets.

**Actual Behavior:**

The buildrunner generates the widgetbook.directories.g.dart file, but imports the widget classes as assets, leading to the inability to find the actual widgets and include them in the Widgetbook.

**Additional Information:**

Flutter version: 3.10.5

dependencies:
  flutter:
  widgetbook_annotation: ^3.0.0-rc.2
  widgetbook: ^3.0.0-rc.2

dev_dependencies:
  build_runner: ^2.3.3
  widgetbook_generator: ^3.0.0-rc.2

Please find the example repository that demonstrates this issue: https://github.com/Bassiuz/widgetbook_test_setup

I would greatly appreciate any help or guidance on resolving this issue. Thank you!

**Comment by Bassiuz** [comment]
I did some research in this case. I think whenever 'source_gen' finds something that is out of the lib path it cannot create a 'package:xxx' import and treats is as an 'asset'. This will prevent files that have use cases but are outside of the /lib/ folder from working.

I wrote a suggestion in how we can convert a asset import to a relative import by specifying the location of the widgetbook.dart file. https://github.com/Bassiuz/widgetbook/pull/1

In this case it is by default looking at '/test/' (conveniently where I want it :) )  It removes the asset part from the import and converts it to a relative import based on the location of the widgetbook.dart file.

Since it is a suggestion it still needs tests. Also it should have a good way to provide the location of the widgetbook.dart file, or preferably automatically find where it is.

What do you think of this approach?

**Comment by YoussefRaafatNasry** [comment]
@Bassiuz Thanks for taking the time to come up with these suggestions.
I will be looking into them soon and see what else we can come up with.

**Comment by Bassiuz** [comment]
Great, no worries. I also want to help myself to finish up this MR to make it mergable if that helps. The only problem I had was if you know of a clean way of detecting where the widgetbook.dart file is located. Currently it defaults to /test/ if its not in the main folder; but it can be located somewhere else (maybe someone wants to put it in a seperate /widgetbook/ folder for example. If we can detect where the widgetbook.dart file is we can automate that parameter.

We could also just have an optional .yml configuration file where we can configure the location of the widgetbook.dart file. But it feels a bit weird to have a configuration yaml with only one function.

**Comment by YoussefRaafatNasry** [comment]
@Bassiuz You can achieve that by providing a [build configuration](https://pub.dev/packages/build_config#configuring-builders-applied-to-your-package)'s `options` key.

But I am not personally a fan of introducing changes that users will need to touch their `build.yaml`, and I prefer working-out-of-the-box solutions. I am currently investigating one promising solution, and I will let you know once we have a working example.

**Comment by YoussefRaafatNasry** [comment]
@Bassiuz Thanks for your efforts on solving this issue. I have a PR that's inspired from your solution that works will all kind of folders not just `test` folder (same result you wanted to achieve).

It would be great if you can validate that this solution works for you by using the `widgetbook_generator` package from GitHub as follows:

```yaml
dev_dependencies:
  widgetbook_generator:
    git:
      url: git://github.com/widgetbook/widgetbook.git
      path: packages/widgetbook_generator/
      ref: fix/asset-imports
```

**Comment by Bassiuz** [comment]
Hey @YoussefRaafatNasry ; this works like a charm! And the fix is so elegant too :)
