### ISSUE TITLE
Inconsistency between docs: `ThemeAddon` and `CustomThemeAddon` 

### ISSUE THREAD

**Issue by dromerolovo** [widgetbook/widgetbook#783]
Could be misleading.

`ThemeAddon` now replaces `CustomThemeAddon`, according to [PR #653](https://github.com/widgetbook/widgetbook/pull/653), the api and the example [`custom_theme_example` ](https://github.com/widgetbook/widgetbook/blob/main/examples/custom_theme_example/lib/app_theme.dart)

But the last example of the [official documentation custom-theme-addon](https://docs.widgetbook.io/addons/theme-addon#custom-theme-addon), **Example: CustomThemeAddon** still uses `CustomThemeAddon`

**Comment by YoussefRaafatNasry** [comment]
Thanks @dromerolovo for reporting this!
We have an open PR (#768) that will get this fixed.
