### ISSUE TITLE
Cannot align widgets outside of use case functions

### ISSUE THREAD

**Issue by jmatth** [widgetbook/widgetbook#787]
**Description**

In Widgetbook 2 I had the use case builder configured to center all use cases. In Widgetbook 3 this is no longer possible. Adding a `Center` or `Align` widget to `appBuilder` has no effect, and neither does implementing adjustable alignment via an Addon as proposed in #654.

The culprit seems to be [this use of `Scaffold` in `workbench.dart`][1]. This Scaffold is inserted into the widget tree below the `appBuilder` or any of the builders from Addons and expands to fill all available space. Removing the Scaffold allows alignment changes from higher in the widget tree to take effect.

Unfortunately removing the scaffold didn't obviously break anything for me but I'm guessing it's there for a reason, so I'm not sure what the next steps in a fix would be.

[1]: https://github.com/widgetbook/widgetbook/blob/35681ed533d701b6c95ef921074012f8577d9ec9/packages/widgetbook/lib/src/workbench/workbench.dart#L35

**Comment by YoussefRaafatNasry** [comment]
Thanks for reporting this issue, @jmatth!
The `Scaffold` was there for the surface background color of the `Workbench`.
I will replace it with a `ColoredBox` iniside the `ThemeAddon` and that should do the job.

**Comment by YoussefRaafatNasry** [comment]
This is now on `main`, you can give it a try and re-open the issue if it is not fixed.
We are also planning on adding the `AlignmentAddon` soon.
