### ISSUE TITLE
Knobs not Working with `StatefulWidget`s

### ISSUE THREAD

**Issue by natt-han** [widgetbook/widgetbook#788]
**Description**
State of statefulwidget was reset after knobs changed.

**Steps To Reproduce**
1. Checkout v3.0.0 and Running the knobs_example in the repo. 
2. Click button to increse counter then 
3. Changing some knobs. 
4. Counter will reset to 0.

**Expected Behavior**
UI Should be able to change without counter reset.

**Additional Context**
3.0.0-rc1 not have this issue.

**Comment by YoussefRaafatNasry** [comment]
This is probably a side-effect of the fix done in #720.
I will look more into possible fixes that can resolve both issues at the same time.

**Comment by aloisdeniel** [comment]
In the meantime you can define a global key for your use case :

```dart
final _key = GlobalKey();

@widgetbook.UseCase(name: 'Example', type: Example)
Widget example(BuildContext context) {
     return KeyedSubtree(
        key: _key,
        child:  / ** **/
    );
}

```

**Comment by daohoangson** [comment]
I want to investigate this issue, can you assign it to me? @YoussefRaafatNasry

**Comment by YoussefRaafatNasry** [comment]
@daohoangson I've assigned you, good luck with your investigation!
On a side note, the solution for this issue should also work with the example [here](https://discord.com/channels/879618555560218625/1115298169878757456). I will try to add a test for that, but feel free to do it in your PR as well.

**Comment by daohoangson** [comment]
Your link just goes to the `release-notes` Discord channel, can you elaborate a bit more?

**Comment by YoussefRaafatNasry** [comment]
@daohoangson Oops, I didn't realize that we made this channel private. I have updated the visibility of the channel and you can now see the thread.

**Comment by daohoangson** [comment]
Thank you, the link works now.

**Comment by daohoangson** [comment]
I have submitted #941 as a potential fix, can you @YoussefRaafatNasry take a look please?

The idea is to avoid using a key for the most typical use of Widgetbook, which is stateless widgets. In cases where the app has a stateful widget, provider, or similar, the `UseCaseBuilder` has check-ins to detect this and apply a key to trigger the required rebuild. This approach strikes a balance, as it optimizes performance for the majority of apps. In the occasional exceptional scenario, Widgetbook can intelligently apply the key, simplifying the adoption process for app developers.

Furthermore, for the exceedingly rare instances when the app explicitly wishes to prevent a rebuild, it's still possible to opt-out with a `GlobalKey`.

**Comment by YoussefRaafatNasry** [comment]
@daohoangson Apology for the late response, we currently have a lot of activity going for Hacktoberfest.
I need more time to investigate the solution you proposed and dig deep to know the root of the issue.
I will do so in the upcoming couple of days and get to you the soonest.

Thanks a lot for trying to improve Widgetbook 💙

**Comment by YoussefRaafatNasry** [comment]
Hello @daohoangson 👋 
Do you think that #979 is kinda related to this issue as well?
Maybe fixing that issue could result in fixing this one.

**Comment by daohoangson** [comment]
It could be related but the demo in the ticket is logging in the constructor, which is expected to be called multiple time. I'll investigate further.

**Comment by YoussefRaafatNasry** [comment]
So after some discussions with the team, we've decided that "reseting `StatefulWidget`'s state after knobs change" will be the default behavior, and the solution suggested by @aloisdeniel can be used to opt-out of that behavior.

The reason we have taken that decision is because of the following case:
Consider a `SteppedCounter` that takes a step as an input, and turns red for all even numbers that are greater than 2.
If the `step` parameter was changed in runtime (from 1 to 2) through `knobs` then reaching the unique red count state of 4 would be impossible, thus the widget should be tested from the original state again to reach this faulty state.

![image](https://github.com/widgetbook/widgetbook/assets/41103290/6014a45e-6b85-4e70-9d2c-abac5ec8c3ef)


I've added an example [here](https://github.com/widgetbook/widgetbook/blob/main/examples/full_example/lib/components/stepped_counter.dart), with the solution suggested by @aloisdeniel, to make it easier for users to find this workaround.
I would like to also thank @daohoangson so much for his efforts and patience in #941

**Comment by EArminjon** [comment]
> So after some discussions with the team, we've decided that "reseting `StatefulWidget`'s state after knobs change" will be the default behavior, and the solution suggested by [@aloisdeniel](https://github.com/aloisdeniel) can be used to opt-out of that behavior.
> 
> The reason we have taken that decision is because of the following case: Consider a `SteppedCounter` that takes a step as an input, and turns red for all even numbers that are greater than 2. If the `step` parameter was changed in runtime (from 1 to 2) through `knobs` then reaching the unique red count state of 4 would be impossible, thus the widget should be tested from the original state again to reach this faulty state.
> 
> ![image](https://github.com/widgetbook/widgetbook/assets/41103290/6014a45e-6b85-4e70-9d2c-abac5ec8c3ef)
> 
> I've added an example [here](https://github.com/widgetbook/widgetbook/blob/main/examples/full_example/lib/components/stepped_counter.dart), with the solution suggested by [@aloisdeniel](https://github.com/aloisdeniel), to make it easier for users to find this workaround. I would like to also thank [@daohoangson](https://github.com/daohoangson) so much for his efforts and patience in [#941](https://github.com/widgetbook/widgetbook/pull/941)

Hello @yousinix,

To reset a use case’s state, the user can exit and re-enter it. Resetting the state every time a parameter changes feels like an odd technical choice in most cases.

Imagine exposing a complex widget with many interactions (click, hover, disable, active, etc.) and numerous properties (colors, borders, sizes). You definitely wouldn’t want the use case to reset every time you tweak something.

Take a real-world example like Figma: when you modify a property, the view doesn’t reset. To get back to the original state of a page, you leave it and then re-enter it.

What do you think ? cc https://github.com/widgetbook/widgetbook/issues/1824
