### ISSUE TITLE
Navigation Panel Loses Focus on Refresh

### ISSUE THREAD

**Issue by YoussefRaafatNasry** [widgetbook/widgetbook#796]
> Only thing is that without the extra code to set up the state before first render on a refresh it fails to render the navigation lozenge until the use case is changed.
> 
> <img width="611" alt="Screen Shot 2023-06-30 at 9 10 49 am" src="https://github.com/widgetbook/widgetbook/assets/7088248/73ae89ad-7a6f-4237-9da7-281bb749c4a7">
> 
> From poking at it yesterday, it looks like a race condition (of sorts) in Flutter. Based on logging things out, I think it plays out like this:
> 1) WidgetbookState has path = null
> 2) WidgetbookShell is created and built with path = null
> 3) NavigationPanel (1) is created with path = null
> 4) NavigationPanel (1) is allocated to an Element
> 5) WidgetbookState updated to path = XXXXX
> 6) WidgetbookShell is rebuilt with path = XXXXX
> 7) NavigationPanel (2) is created with path = XXXXX
> 8) NavigationPanelState is built *still referencing NavigationPanel(1)*
> 
> Between (7) & (8) the widget should be replaced, but isn't. I don't understand the internals well enough to know why though. 
> 
> I've stopped being lazy and moved my changes over to a [branch](https://github.com/jamesgorman2/widgetbook/blob/preserve-state-on-refresh/packages/widgetbook/lib/src/widgetbook.dart) if you want to look at what I did again.
> 
_Originally posted by @jamesgorman2 in https://github.com/widgetbook/widgetbook/issues/782#issuecomment-1613917396_

**Comment by khurramrizvi** [comment]
Please assign this issue to me, I would like to contribute.
