### ISSUE TITLE
Permanent dark background

### ISSUE THREAD

**Issue by Maxim-Filimonov** [widgetbook/widgetbook#803]
**Versions:**
- widgetbook: 3.1.0
-  widgetbook_annotation: 3.0.0

**Description**
It seem that widget book defaults to dark background without ability to override this behaviour. 
As Flutter uses dark as default color for fonts it becomes impossible to see many text elements and it's not very obvious that text is just written dark on dark.
I did try to manually override theme but that didn't work either.
```
// widgetbook.dart
 var lightTheme = WidgetbookTheme(name: 'Light', data: ThemeData.light());
    return Widgetbook.material(
      addons: [
        AlignmentAddon(),
        ThemeAddon(
          themes: [
            lightTheme,
            WidgetbookTheme(name: 'Dark', data: ThemeData.dark())
          ],
          initialTheme: lightTheme,
          themeBuilder: (context, ThemeData theme, child) =>
              Theme(data: theme, child: child),
        ),
      ],
```

**Steps To Reproduce**

1. Download full_example from latest master
2. pub get
3. flutter run -d macos -t lib/widgetbook.dart             
4. Look at Custom Container, CustomTextField use cases it seem there is nothing there.

**Expected Behavior**
To be able to customise default background with theme.

**Screenshots**
![CleanShot 2023-07-03 at 17 25 58](https://github.com/widgetbook/widgetbook/assets/360645/4f514d54-cdcb-4eac-9907-3c6bed0dcdd9)

**Comment by Maxim-Filimonov** [comment]
@mishkaowner thanks for pointing it out.
Downgrading to 3.0.0 solved the problem for now for me.

**Comment by YoussefRaafatNasry** [comment]
The addons **order matter**, because each addon is wrapping all your uses-cases in a Widget (for exampel `ThemeAddon` wraps your use-cases in `Theme` widget). So wrapping `Theme` Widget in a `Align` Widget, doesn't allow `Theme` to fill the whole workbench area, causing the whole area to have the default color added in #800

Ordering the addons as follow will solve your problem:
1. `DeviceFrameAddon` (if any)
1. `ThemeAddon`
1. `AlignmentAddon`

**Comment by Maxim-Filimonov** [comment]
@YoussefRaafatNasry I tried that:
``` 
 var lightTheme = WidgetbookTheme(name: 'Light', data: ThemeData.light());
 addons: [
        ThemeAddon(
          themes: [
            lightTheme,
            WidgetbookTheme(name: 'Dark', data: ThemeData.dark())
          ],
          initialTheme: lightTheme,
          themeBuilder: (context, ThemeData theme, child) =>
              Theme(data: theme, child: child),
        ),
        AlignmentAddon(), 
```
That didn't have any effect -> with 3.1.0 still background is dark.

**Comment by YoussefRaafatNasry** [comment]
@Maxim-Filimonov

The `Theme.of(context).scaffoldBackgroundColor` is used as a background color for workbench when a device frame is active, this should match Widgetbook's theme and not the App's theme.

![image](https://github.com/widgetbook/widgetbook/assets/41103290/1e6c5bd1-4c1c-4b6d-9632-1d78e1685c43)

**Comment by Maxim-Filimonov** [comment]
@YoussefRaafatNasry I see. 
Doesn't it mean that when I set light theme it should change background to white inside the device frame ?

**Comment by YoussefRaafatNasry** [comment]
> Doesn't it mean that when I set light theme it should change background to white inside the device frame ?
@Maxim-Filimonov Yes, that's right.
It is not working fo you because you are using [`ThemeAddon`](https://docs.widgetbook.io/addons/theme-addon) and not `[MaterialThemeAddon`](https://docs.widgetbook.io/addons/theme-addon#material-theme-addon).

```dart
MaterialThemeAddon(
  themes: [
    WidgetbookTheme(name: 'Light', data: ThemeData.light());
    WidgetbookTheme(name: 'Dark', data: ThemeData.dark())
  ],
),
```
