### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by Kiruel** [widgetbook/widgetbook#805]
**Description**
Today widgetbook can only be used in large screen but not in mobile.

**Expected Behavior**
Should be possible to use widget book in responsive mode.

**Comment by reyhanlioglu** [comment]
I can use widgetbook in a mobile phone at landscape mode without any problem and it's quite responsive. What is the problem that blocking you to do it?

**Comment by Kiruel** [comment]
I mean use it in real Android phone.

**Comment by bramp** [comment]
A similar open source library, https://pub.dev/packages/storybook_flutter has a feature that when you are on a small device, they hide the list of widgets and knobs behind a menu that pops open when clicked. This enables both small and large format displays.

It is very useful to test the widgets on a real handheld android/iOS devices, as that enables you to test they actually feel/respond/look correct. So +1 to this.

**Comment by YoussefRaafatNasry** [comment]
After discussions with the team on how to support Widgetbook on mobile, we came up with the following wireframe:

1. The design on big screens will be the same without any change.
1. The design on smaller screens will have a bottom bar with three icons: navigation, addons, knobs.
1. When any icon is pressed from the bottom bar, a bottom modal sheet opens.
1. The bottom modal sheets should be expandable (you can pull to top to expand, or pull to bottom to close them).

![image](https://github.com/widgetbook/widgetbook/assets/41103290/5c0a93d5-1c87-4083-a30c-131dd1607cec)

**Comment by Mastersam07** [comment]
Hi @YoussefRaafatNasry assign this to me. Would like to take a look at it

**Comment by Kiruel** [comment]
Sounds good ! Thanks for sharing your proto !

**Comment by YoussefRaafatNasry** [comment]
Hello @Mastersam07 👋 
Are you still planning to work on this?

**Comment by Mastersam07** [comment]
Hi @YoussefRaafatNasry been kind of occupied recently.

Sent a draft PR in #1019. 

Will update it in a fews and mark it ready for review.

**Comment by Mastersam07** [comment]
Hi @YoussefRaafatNasry , the behavior:

>>> We also want to add a gesture (e.g. four fingers tap) to show/hide the bottom bar (i.e. enable full screen mode).

Is it core/an acceptance criteria?

**Comment by YoussefRaafatNasry** [comment]
@Mastersam07 We can add it later in a different PR, no worries about it.

**Comment by Mastersam07** [comment]
> @Mastersam07 We can add it later in a different PR, no worries about it.

Alright. I have marked #1019 as ready for review.

**Comment by Kiruel** [comment]
Thanks for the feature ! Can we create a new version to include this feature ? (I don't know how you handle your build version if it's need to be tested before etc...).

**Comment by YoussefRaafatNasry** [comment]
Hello @Kiruel 👋 
A release is in progress, it will available in the next few days 🎉

**Comment by YoussefRaafatNasry** [comment]
@Kiruel The release has just been _secretly_ published, we will announce it in a few days after we are done with some content, but you can start using it now.
