### ISSUE TITLE
Should be possible to pass an image url in knobs that refresh the image

### ISSUE THREAD

**Issue by Kiruel** [widgetbook/widgetbook#806]
**Description**
Should be possible to pass an image url in knobs that refresh the image.

**Steps To Reproduce**

If I'm using:
```dart
NetworkImage(context.knobs.string(
        label: 'Image Url',
        initialValue:
            'my_image_url',
      ))
```
Then when I change `my_image_url` by another value, the image is not refreshed.

**Expected Behavior**
Should be possible to change an url value from a string.

**Comment by YoussefRaafatNasry** [comment]
This is no longer reproducible on `main`, it was a side-effect fix of #817
