### ISSUE TITLE
fix(generator): `directories` variable cannot be assigned to `Widgetbook`s property when empty

### ISSUE THREAD

**Issue by jenshor** [widgetbook/widgetbook#808]
**Description**
When a new Widgetbook is set up with an empty `directories` variable via the code generation approach, the array is empty and therefore its type is `List<dynamic>` as its type is not specified. 
The type of `List<dynamic>` cannot be assigned with the expected `List<MultiChildNavigationNodeData>` from the `Widgetbook` widget's `directories` property.

**Comment by Alice-in-korea** [comment]
same issue!
