### ISSUE TITLE
Use addons conditionally

### ISSUE THREAD

**Issue by outring** [widgetbook/widgetbook#811]
**Description**

I'm developing a whole new theme using the Widgetbook. The theme consists not only of components but also of predefined colors, sizes, font styles, etc. For the regular components I would like to use the device frame addon but it's shouldn't affect the `WidgetbookCategory`/`WidgetbookComponent` nodes of the foundation styleguide with all the primitives mentioned above

I was looking at the current addons API and it appears that there's no way for an addon to understand which node it's going to display. I see a potential way of having some link between `addon` and `integration` since the integration have the `onChange` but this link will be working outside of the build context (via some outer scope variable or widgetbook host component state). The better way would be to use a context and have bottom-to-top (`WidgetbookUseCase`-to-`WidgetbookAddon`) data propagation to conditionally disable the addon. But even this approach doesn't feel right so I wonder if there's a better way to do it you can think of or maybe, if you believe it's a good feature to have, you can add it to your roadmap and if you can provide the desired implementation details I'll try to help with the actual PR depending on the amount of time it requires

I think the optimal implementation could look like an `addons` property in `WidgetbookCategory`/`WidgetbookComponent` which will stack on top of the global addons list 🤔 

And thanks for the awesome library, I'm enjoying it much more than its web counterparts 😅 cheers

**Comment by outring** [comment]
I found a way to make it work by overloading an addon's `buildUseCase` and `buildFields` combined with resolution of `WidgetbookState` from the build context (didn't realize it was possible). There's only one small bug for which I'm preparing the PR now

**Comment by YoussefRaafatNasry** [comment]
> I found a way to make it work

@outring Is this issue still blocking you by any means?

**Comment by outring** [comment]
Hi @YoussefRaafatNasry. Now, it doesn't, the workaround with overriding build methods of `DeviceFrameAddon` proved to be working good. Here's an example in case somebody will need this:
```
class _DynamicDeviceFrameAddon extends DeviceFrameAddon {
  _DynamicDeviceFrameAddon({required super.devices, super.initialDevice});

  @override
  Widget buildFields(final BuildContext context) {
    if (!_isEnabled(context)) {
      return SizedBox.shrink();
    }
    return super.buildFields(context);
  }

  @override
  Widget buildUseCase(final BuildContext context, final Widget child, final DeviceFrameSetting setting) {
    if (!_isEnabled(context)) {
      return child;
    }
    return super.buildUseCase(context, child, setting);
  }

  bool _isEnabled(final BuildContext context) {
    final state = WidgetbookState.of(context);
    return state.path?.startsWith('foundation/') == false;
  }
}
```

**Comment by YoussefRaafatNasry** [comment]
@outring that's a good solution! 
Glad you figured it out 🎉
