### ISSUE TITLE
Widget properties controller

### ISSUE THREAD

**Issue by octobrekids** [widgetbook/widgetbook#83]
I wished if I can control the widget properties value such as if I have a `Button` widget which I have a text property, so I can input the button text and see the widget appearance changes immediately, or if I have a check box I can control the properties to show the checked or un-checked checkBox.

**Comment by JensHor** [comment]
Thanks for opening an issue 😊  What you are referring to is called 'knobs' and we are already tracking the issue here: #21. Therefore, i am closing this issue.
