### ISSUE TITLE
Incorrect Offset within `DeviceFrameAddon`

### ISSUE THREAD

**Issue by ggirotto** [widgetbook/widgetbook#865]
**Description**

I have a Widget that dynamically adds and removes an element from the screen. This Widget that is dynamically positioned in the screen is build using `OverlayEntry`. Here's an example of it:

```dart
OverlayEntry(
      builder: (context) {
        final textFieldRender = _textFieldKey.currentContext?.findRenderObject() as RenderBox?;
        if (textFieldRender == null) return Container();

        final textFieldOffset = textFieldRender.globalToLocal(Offset.zero);

        return Positioned(
          top: _hasSpaceBelow
              ? textFieldOffset.dy.abs() + textFieldHeight
              : textFieldOffset.dy.abs() - _optionsContainerHeight,
          left: max(0, textFieldOffset.dx.abs()),
          right: max(0, textFieldOffset.dx.abs()),
          height: 200,
          child: Container(), // Child
        );
      },
    )
```

And this widget is placed using `Overlay.of(context).insert(<WIDGET>);`

It works as expected in the iOS and Android simulators, but it behaves oddly in the Widgetbook website. The issue seems to be kind of obvious: the web viewport is way bigger than the simulator screen, so it doesn't make sense to use the same logic here. So the question is: is it possible to calculate the coordinates using the device viewport as a reference?

I see that `globalToLocal` has a `ancestor` param. If I had access to the device widget, I could use it as ancestor, just not sure how to get it.

**Comment by YoussefRaafatNasry** [comment]
Hello @ggirotto 👋 
Apology for the late response.

I will be looking more into a solution for this issue, but in the meantime, it would be great to provide a **reproduction repo** from your side, to reproduce the initial problem or what you are trying to achieve in the first place, just to make sure we are solving the right problem here.

**Comment by ggirotto** [comment]
For sure! I'm attaching a reproducible example of the issue in this comment.

Basically I added a simplified version of the Widget that I'm trying to use in both projects: my main mobile (iOS and Android) app and in the Widgetbook website. You can check the widget in `component.dart`.

I added two `main` files to this reproducible example. The `main.dart` is the version that runs in mobile simulators or devices and `main_web.dart` the one that runs the Widgetbook library in a web page.

The result of running the widget in the mobile project is like this:

<details>
<summary>Screenshot</summary>

![Simulator Screenshot - iPhone 14 - 2023-08-30 at 09 56 02](https://github.com/widgetbook/widgetbook/assets/11745745/d0376f2b-e440-428d-bbcd-a62a75d9cf48)

</details>

The dropdown container is correctly placed right below the field. But this doesn't work in the web example running widgetbook due to the reasons explained in this issue description.

To run the mobile:

`flutter run --target lib/main.dart`

To run the web:

`flutter run --target lib/main_web.dart`

I hope this helps to investigate a possible solution to this.

[bug.zip](https://github.com/widgetbook/widgetbook/files/12475762/bug.zip)

**Comment by YoussefRaafatNasry** [comment]
This issue is related to [device_frame](https://pub.dev/packages/device_frame) package,
you can find a relevant issue here: aloisdeniel/flutter_device_preview#76.

I cannot think of any workaround now from our side, but I will let you know if something popped up.

**Comment by ggirotto** [comment]
@YoussefRaafatNasry Thanks for the feedback!

Is there any way of wrapping the Device Frame widget and expose access to its wrapper or key? Maybe an widget that could be discovered in the three using `findAncestorStateOfType` or something like that? If we can have access to the Widget that wraps the device frame, we could use the `ancestor` param of `globalToLocal` method.

**Comment by YoussefRaafatNasry** [comment]
@ggirotto I am afraid that doing so will make you Widget dependent on Widgetbook, and might break it in the actual app.

**Comment by ggirotto** [comment]
Yep, I agree, but I was thinking about doing this in the less intrusive way as possible. Something like

```dart
MyWdiget {
  MyWdiget({Key? ancestorKey, ...});
}
```

And use this optional ancestor key when provided, otherwise don't use it, and I would provide this key only in the Widgetbook context.

**Comment by YoussefRaafatNasry** [comment]
@ggirotto You can try achieving that with a [custom addon](https://docs.widgetbook.io/addons/custom-addon).
On the other hand, we are looking to replace [`device_frame`](https://pub.dev/packages/device_frame) package by our internal implementation.

**Comment by ggirotto** [comment]
That's a good idea, thanks for the suggestion!
As soon as I have some time I'll try to make it using a custom addon.
Do you have a timeline about the next moves for the widgetbook project to know when `device_frame` would be replaced?

**Comment by YoussefRaafatNasry** [comment]
We are currently investigating the internal alternative to `device_frame`, this might take a while, but the results are promising. We will try our best to get it out in the next release if we were satisfied with the final result.

**Comment by ggirotto** [comment]
Hey @YoussefRaafatNasry , thanks for the suggestion!
The problem that I found is that it consider the entire "box" in which the device frame is placed in, and not just the device frame. See the following screenshot

<img width="909" alt="CleanShot 2023-09-13 at 09 21 55" src="https://github.com/widgetbook/widgetbook/assets/11745745/e0d21d59-7e00-4a84-866c-b479b97a2ce7">

**Comment by YoussefRaafatNasry** [comment]
@ggirotto Can you try reordering the `addons` as follows?

```dart
addons: [
  DeviceFrameAddon(...),
  KeyedAddon(),
],
```

**Comment by YoussefRaafatNasry** [comment]
I assume that the `KeyedAddon` solved this issue, so I will close this until proven otherwise.
