### ISSUE TITLE
Use custom title & include custom logo

### ISSUE THREAD

**Issue by SimoneSchaefer** [widgetbook/widgetbook#892]
**Description**

Hello dear widgetbook team, 
thanks for your amazing package :)

I have two questions: 

**How to set a custom title?**

I use widgetbook in the web and did not find any way yet to set a nice title to be displayed in the browser. 
I set the   `<meta name="apple-mobile-web-app-title" content="...">` and the `<title>` tag in the index.html. 
I also set the title in the appBuilder like this: 

```
appBuilder: (context, child) {
  return MaterialApp(
    title: 'My custom title',
    home: child,
   );
},
```
The result is that the custom title is shown during loading, but disappears one loading is done (and just displays the URL).  What am I missing?

**Is it possible to include a custom logo?**

I want to display a small logo in the left navigation bar, directly above the search box. Is there any way to achieve this?

**Comment by YoussefRaafatNasry** [comment]
Hello @SimoneSchaefer 👋 
We have merged #878 to `main`, it sets the title to `Widgetbook`.
And for the icon customization, I believe it can be done from the app you have Widgetbook.
It's hard to achieve that now with our current setup.

![Screenshot 2023-09-15 at 4 30 55 PM](https://github.com/widgetbook/widgetbook/assets/41103290/23174795-bf5e-46c0-9a22-2e4b1c40fbe1)
