### ISSUE TITLE
Nullable Double Slider Knob's `initialValue` Cannot be `null`

### ISSUE THREAD

**Issue by kekland** [widgetbook/widgetbook#901]
**Description**
When using `context.knobs.doubleOrNull.slider()` with an `initialValue: null`, the initial value is set to a non-null value.

**Steps To Reproduce**

1. Use a nullable double slider knob and set its initial value to `null`
2. When the story is opened, the value of the knob is non-null by default

**Expected Behavior**
I would expect that if the `initialValue` is set to `null`, then it would be respected by the knob.

**Additional Context**
This line here https://github.com/widgetbook/widgetbook/blob/4aae40f24af8e047b02ac99169c8dcdc06ea2787/packages/widgetbook/lib/src/knobs/builders/double_knobs_builder.dart#L68 might be the issue

**Comment by YoussefRaafatNasry** [comment]
Hello @kekland 👋 
It makes sense to remove the default value, I think this line has been carried along since `v3-beta`.

The fix will be included in our [Hacktoberfest](https://hacktoberfest.com/) Release.

**Comment by Utkarsh4517** [comment]
Will love to work on this issue, Can you assign me?

**Comment by Utkarsh4517** [comment]
Hey Actually I am facing some issues setting up the project, 
I ran this command first
`flutter pub run build_runner build`
but it said build  runner was not installed, So I installed it using this command `dart pub add build_runner --dev`
after that I again run `flutter pub run build_runner build` 

Got this as an output 
`Built build_runner:build_runner.
[INFO] Generating build script completed, took 279ms
[INFO] Precompiling build script... completed, took 7.2s
[INFO] Building new asset graph completed, took 488ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Running build completed, took 2ms
[INFO] Caching finalized dependency graph completed, took 58ms
[INFO] Succeeded after 69ms with 0 outputs (0 actions)`

It succedded but in Sandbox/lib/widgetbook.dart on import of `import 'widgetbook.directories.g.dart';` It's giving an error as 

Target of URI hasn't been generated : `'widgetbook.directories.g.dart'`. Try running the generator that will generate the file referenced by the URI.

**Comment by YoussefRaafatNasry** [comment]
Hello @Utkarsh4517 👋 

it's probably because we use [Melos](https://melos.invertase.dev/) for package management. We've just published a new [contribution guide](https://docs.widgetbook.io/contribution/get-started) that will help you setup your development environment.
