### ISSUE TITLE
Add `designLink` to `WidgetbookUseCase`

### ISSUE THREAD

**Issue by YoussefRaafatNasry** [widgetbook/widgetbook#902]
The `@UseCase` annotation has an optional parameter called `designLink` which can hold a URL to the Figma design. This parameter was primarly used for Widgetbook Cloud, but we want to make it available in `widgetbook` package as well, by adding it to the `WidgetbookUseCase` class. The new field will allow creating addons that can launch the given url or showing a side-by-side comparison.

**Comment by saurav0523** [comment]
i want to work on  this issue

**Comment by saurav0523** [comment]
Is this the part of hacktoberfest

**Comment by YoussefRaafatNasry** [comment]
@saurav0523 Yes, it is.

**Comment by saurav0523** [comment]
i have done flutter pub get and still got an error, can you please suggest me where i'm doing wrong

**Comment by YoussefRaafatNasry** [comment]
Hello @saurav0523 👋 
I am so sorry but @Mastersam07 already have started working on this issue in #926.
But the good new is that there is still a lot of issues in Hacktoberfest, so keep it up, we will wait for your next issue.

And concerning the error you have, it's probably because we use [Melos](https://melos.invertase.dev/) for package management. We've just published a new [contribution guide](https://docs.widgetbook.io/contribution/get-started) that will help you setup your development environment.

**Comment by saurav0523** [comment]
okkk

**Comment by yousinix** [comment]
Hello @vasilich6107 👋 

You can get the `designLink` for the active use-case as follows:

```
final designLink = WidgetbookState.of(context).useCase?.designLink;
```
