### ISSUE TITLE
Add Light Theme Support

### ISSUE THREAD

**Issue by bramp** [widgetbook/widgetbook#905]
**Description**
The Widgetbook seems to use a dark theme. That is, all the stuff around the app under test, e.g the list of widgets down the left, and addon/knobs on the right. 

It would be useful if that theme would inherent from the system's defaults, and/or be customisable. Specifically on my machine the dark theme is hard to read, and I'd much prefer a light theme.

**Steps To Reproduce**

1. Create a Widgetbook
2. Run

**Expected Behavior**

The widgetbook uses the system's theme, not explicitly setting dark.

**Screenshots**

**Additional Context**

It seems as simple as applying the following patch to lib/src/widgetbook.dart

```
❯ diff widgetbook.dart-theme widgetbook.dart
--- widgetbook.dart-theme	2023-09-28 19:35:52
+++ widgetbook.dart	2023-09-28 19:36:06
@@ -128,7 +128,9 @@
       state: state,
       child: MaterialApp.router(
         title: 'Widgetbook',
-        theme: Themes.dark,
+        theme: Themes.light(),
+        darkTheme: Themes.dark(),
+        themeMode: ThemeMode.system,
         routerConfig: router,
         debugShowCheckedModeBanner: false,
       ),
```

**Comment by 07Abhinavkapoor** [comment]
Hey @YoussefRaafatNasry ,
Could you please provide the light scheme color values needed to address the issue?

**Comment by YoussefRaafatNasry** [comment]
@07Abhinavkapoor Unfortunately the color scheme is not currently available as values, but you can easily extract them as follows:

1. Open the [Theme SVG](https://github.com/widgetbook/widgetbook/assets/41103290/cf29cc5b-a96c-4190-9efc-40008192cfec) in any browser.
1. Enter the "inspect" mode in your browser.
1. Hover over each tile and get the color HEX value.

**Comment by saurav0523** [comment]
i want to work on this issue

**Comment by YoussefRaafatNasry** [comment]
@saurav0523, the bad news is that @07Abhinavkapoor has already worked on this.
The good news is, we will finally have a light theme soon!
