### ISSUE TITLE
Hacktoberfest 2023 in here!  

### ISSUE THREAD

**Issue by mhadaily** [widgetbook/widgetbook#918]
Hacktoberfest annually unites maintainers and new contributors in an open-source celebration. Widgetbook enhanced the main DigitalOcean event this year, hosting a month for Flutter and Dart devs worldwide to contribute to our repository.

### Successful Hacktoberfest Pull Requests
Please only submit high-quality pull/merge requests. Please refer to [Hacktoberfest Quality Guidelines](https://hacktoberfest.com/participation/) to understand better how we validate contributor requests.

1. **Originality:** All issues under our repository
2. **Relevance:** Merged and tagged with `hacktoberfest-accepted`
3. **Timeframe:** Submitted between 1st October and 31st October
4. **Technical Execution:** Meaningful, adds value, and contributes to the success of the repository
5. **No Spam:** Avoid spamming! You will be blocked from the program if you repeat this!
6. **Overall Impact:** Do not send small tweak PR for a repository, such as fixing typos!

### Rewards
On top of what you will receive from the Digital Ocean, we will also ship you one of our **unique design T-shirts and sticker packs.** 

-------
Have questions? let's us know under this issue.

**Comment by antonio-pedro99** [comment]
This year there won't be any physical swags such t-shirts and stickers :(

**Comment by mhadaily** [comment]
> This year there won't be any physical swags such t-shirts and stickers :(

You have a chance to get a Widgetbook Tshirt then 😄

**Comment by antonio-pedro99** [comment]
> > This year there won't be any physical swags such t-shirts and stickers :(
> 
> You have a chance to get a Widgetbook Tshirt then 😄

Awesome

**Comment by daohoangson** [comment]
This repo is missing the `hacktoberfest` topic.

**Comment by mvarendorff** [comment]
@daohoangson PRs tagged with https://github.com/widgetbook/widgetbook/labels/hacktoberfest-accepted still count towards your hacktoberfest contributions regardless of the repository's topics.

**Comment by geisterfurz007** [comment]
Since this thread is for questions: How do I apply for a T-Shirt after a successfully merged PR? Will there be a unified thread for that, will there be a Google Form posted under qualifying PRs or is there something else that would happen 🤔

**Comment by Devesh1509** [comment]
Hello @mhadaily I am a beginner to open source , and want to contribute can you please guide and suggest me issues to start with ?

**Comment by YoussefRaafatNasry** [comment]
> Since this thread is for questions: How do I apply for a T-Shirt after a successfully merged PR? Will there be a unified thread for that, will there be a Google Form posted under qualifying PRs or is there something else that would happen 🤔

@geisterfurz007 By the end of October, we will announce all the contributors here on this issue and we will post more info about how to claim your swag. Stay tuned! 🎉

**Comment by YoussefRaafatNasry** [comment]
We have reached out to all applicable participants.
Thanks for your contributions everyone 💙

**Comment by boredcity** [comment]
Just to confirm: https://github.com/widgetbook/widgetbook/pull/950 is not included?

**Comment by geisterfurz007** [comment]
I am a bit confused. I did not find a comment under my PR either and that despite having been given a shoutout both on Twitter and a Medium Blog post. I also checked my mail inbox including the spam folder of the account that made the commit but there was nothing there either. So just to make sure I am not missing anything: Where did you reach out @YoussefRaafatNasry?

**Comment by YoussefRaafatNasry** [comment]
Hello @geisterfurz007 👋 
There was a typo in your email address that we have from your personal website.
You should have received another email from us by now. If that's not the case, please reach us out on [this email](mailto:devrel@widgetbook.io) and we will take it from there. 

Apology for the inconvenience 💙

**Comment by YoussefRaafatNasry** [comment]
Anyone who has [participated in Hacktoberfest](https://github.com/widgetbook/widgetbook/pulls?q=is%3Apr+is%3Aclosed+label%3Ahacktoberfest-accepted) and did not receive an email from us _(probably we did not fetch their correct email from the GitHub API)_, please reach us out on [this email](mailto:devrel@widgetbook.io) to claim your swag.
