### ISSUE TITLE
Change the name and icon of twiter to X

### ISSUE THREAD

**Issue by Kaniz-Fatma** [widgetbook/widgetbook#928]
Twitter is now known as X and it has its own icon. It would be great if twitter is changed to X in community.

Screenshot :
![IMG_20231004_120813](https://github.com/widgetbook/widgetbook/assets/146003237/cb29a7a4-d7cb-4ce9-83ce-6b1d9fdf93d8)

**Comment by Kaniz-Fatma** [comment]
At the bottom of the page and above the footer where putted social media platforms. And also there may need some changes in the "stay up to date" section about the icon and name of Twitter (now known as X)
![Screenshot_2023-10-04-12-06-57-56_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/widgetbook/widgetbook/assets/146003237/be5fa9f7-daeb-4449-87e7-fa84628935da)

**Comment by amrahs02** [comment]
please assign this issue to me

**Comment by YoussefRaafatNasry** [comment]
@amrahs02 This ticket is not in Hacktoberfest, and It will be handled by our team, since the landing page is not open-source

**Comment by YoussefRaafatNasry** [comment]
I will be closing this issue as I've forwarded it to our team internally.
And it's not related to the open-source library but to the landing page.
Thanks for keeping a fresh eye on these little details tho 💙
