### ISSUE TITLE
Add Website Links to READMEs

### ISSUE THREAD

**Issue by Arkaroy147** [widgetbook/widgetbook#946]
Wish to modify the Readme.md such that upon clicking on the icon, the user will be redirected to widgetbook.io 
Please mark this as hacktoberfest accepted

**Comment by YoussefRaafatNasry** [comment]
Hello @Arkaroy147 👋 
Please do so for all packages' README as well and not just the root README file.
You can also hyperlink the screenshot in [widgetbook/README](https://github.com/widgetbook/widgetbook/blob/main/packages/widgetbook/README.md) to [demo.widgetbok.io](https://demo.widgetbook.io/).

**Comment by Arcturus22** [comment]
> Hello @Arkaroy147 👋 Please do so for all packages' README as well and not just the root README file. You can also hyperlink the screenshot in [widgetbook/README](https://github.com/widgetbook/widgetbook/blob/main/packages/widgetbook/README.md) to [demo.widgetbok.io](https://demo.widgetbook.io/).


@YoussefRaafatNasry 
I understood what you want to be done to this screenshot you linked. What about the other README files?
Do you want the link to be added to the others too?

Would you please assign me this issue? I would like to contribute too.

**Comment by YoussefRaafatNasry** [comment]
@Arcturus22 I prefer if @Arkaroy147 worked on this issue for hacktoberfest, as it was reported by him. Please do not open a PR for this until @Arkaroy147 states that they won't work on it.

And to answer your question, the demo URL should only be added to [widgetbook/README](https://github.com/widgetbook/widgetbook/blob/main/packages/widgetbook/README.md), but the website URL should be added to all READMEs.

**Comment by Arcturus22** [comment]
> @Arcturus22 I prefer if @Arkaroy147 worked on this issue for hacktoberfest, as it was reported by him. Please do not open a PR for this until @Arkaroy147 states that they won't work on it.
> 
> And to answer your question, the demo URL should only be added to [widgetbook/README](https://github.com/widgetbook/widgetbook/blob/main/packages/widgetbook/README.md), but the website URL should be added to all READMEs.

Alright, I will follow that.

I got your point, thanks for the reply.

**Comment by Arcturus22** [comment]
@YoussefRaafatNasry 
May I open a PR now if its not a problem?

**Comment by Arkaroy147** [comment]
updated, please check

**Comment by YoussefRaafatNasry** [comment]
This issue has been removed from Hacktoberfest due to the violation of [rules](https://github.com/widgetbook/widgetbook/issues/918#issue-1921537435) 4 and 6.
