### ISSUE TITLE
Readme file for contribution folder

### ISSUE THREAD

**Issue by ayan-joshi** [widgetbook/widgetbook#951]
**Description**
Readme file for the docs/contribution folder , The contribution have different files which explain deeply about every contribution any developer can make in the repository. So the folder should have a readme file which explains all the contribution in a single file or just give its introduction.

**Steps To Reproduce**

1, Will study all files in the contribution folder
2. Create a readme file with proper description and explanation

**Additional Context**
Please assign me this issue under hacktoberfest label I'm eager to contribute and work on it @YoussefRaafatNasry

**Comment by YoussefRaafatNasry** [comment]
Hello @ayan-joshi 👋 
Are you refering to something like [Quick Guide](https://docs.widgetbook.io/contribution/quick-guide) or [CONTRIBUTING.md](https://github.com/widgetbook/widgetbook/blob/main/CONTRIBUTING.md)?

**Comment by ayan-joshi** [comment]
> Hello @ayan-joshi 👋 Are you refering to something like [Quick Guide](https://docs.widgetbook.io/contribution/quick-guide) or [CONTRIBUTING.md](https://github.com/widgetbook/widgetbook/blob/main/CONTRIBUTING.md)?

No I am talking about docs/contribution folder @YoussefRaafatNasry

**Comment by YoussefRaafatNasry** [comment]
@ayan-joshi, Sorry but I don't see any benefit from adding a README file inside the docs folder as it only used for [docs.widgetbook.io](https://docs.widgetbook.io), can you elaborate more why you think that this will be a good addition?

**Comment by YoussefRaafatNasry** [comment]
I will be closing this for declutter, feel free to discuss it more before you open a PR.

**Comment by ayan-joshi** [comment]
> @ayan-joshi, Sorry but I don't see any benefit from adding a README file inside the docs folder as it only used for [docs.widgetbook.io](https://docs.widgetbook.io), can you elaborate more why you think that this will be a good addition?

A readme file there can help developers and contributors to get a better knowledge of the folder without looking the other files in the folder , that was the reason I had a idea to create a readme file there , it's just enhance the repo doesn't have any problem with it @YoussefRaafatNasry

**Comment by YoussefRaafatNasry** [comment]
@ayan-joshi That will be a great idea if the `docs/` folder was not hosted anywhere, but currently this folder is only for [docs.page](docs.page) and it should be navigated from (docs.widgetbook.io)[https://docs.widgetbook.io/] and not from GitHub.
