### ISSUE TITLE
Broken Docs Links

### ISSUE THREAD

**Issue by Smartmind12** [widgetbook/widgetbook#954]
A list of broken links in the docs:

1. https://docs.widgetbook.io/contribution/quick-guide > MIT license
1. https://docs.widgetbook.io/contribution/code-reviews > MIT license
1. https://docs.widgetbook.io/addons/custom-addon > See Source code
1. https://docs.widgetbook.io/cookbook/custom-theme > See Source code
1. https://docs.widgetbook.io/widgetbook-cli/overview > Widgetbook Review

**Comment by YoussefRaafatNasry** [comment]
Hello @Smartmind12 👋 
Thanks a lot for the docs inspection! Looking forward for your PR.

On a side note, please avoid opening issues for trivial docs changes, and consider opening a PR directly.
I can also see that you have opened 2 more issues (#955, #956), so I will be merging them in one issue here that will be assigned to you.

**Comment by Smartmind12** [comment]
> Hello @Smartmind12 👋 Thanks a lot for the docs inspection! Looking forward for your PR.
> 
> On a side note, please avoid opening issues for trivial docs changes, and consider opening a PR directly. I can also see that you have opened 2 more issues (#955, #956), so I will be merging them in one issue here that will be assigned to you.

Ohh sure i will keep that in mind. I wanted to have a look at the docs before i made code related PR where i saw these issue so i reported! Thanks will do the needful and complete the PR!
