### ISSUE TITLE
Missing link to Widgetbook Review

### ISSUE THREAD

**Issue by Smartmind12** [widgetbook/widgetbook#955]
**Description**

Currently on clicking the widgetbook review it takes you to a dead link giving a 404 error.

**Steps To Reproduce**

1. Go to https://docs.widgetbook.io/widgetbook-cli/overview
2.  Click Widgetbook Review

**Expected Behavior**

The hyperlink should take the user to Widgetbook Reviews page.

**Screenshots**

![Screenshot 2023-10-09 at 12 40 24 AM](https://github.com/widgetbook/widgetbook/assets/91927689/0dac6d12-b899-4edb-9120-746a2c00d0c7)

**Additional Context**
Kindly assign this issue so that i can work on it and rectify the same as a part of Hacktoberfest
.

**Comment by YoussefRaafatNasry** [comment]
Merged into #954
