### ISSUE TITLE
Navigation error of 'See Source Code' Hyperlinks

### ISSUE THREAD

**Issue by Smartmind12** [widgetbook/widgetbook#956]
**Description**

Currently a 404 error arrises on clicking the hyperlink to "See source code" in the Addon page in 2 occassions.

**Steps To Reproduce**

1. Go to https://docs.widgetbook.io/addons/custom-addon
2. Scroll down to "See Source code"
3. Click on "See Source code"

1. Go to https://docs.widgetbook.io/cookbook/custom-theme
2. Scroll down to "See Source code"
3. Click on "See Source code"

**Expected Behavior**

The hyperlink should take the user to the respective source code of the demos on Github.

**Screenshots**

![Screenshot 2023-10-09 at 1 08 55 AM](https://github.com/widgetbook/widgetbook/assets/91927689/174f400e-6cf1-4019-b743-e4e3b7d155f5)

**Additional Context**

Kindly assign this issue so that i can work on it as a part of hacktoberfest and update the links.

**Comment by YoussefRaafatNasry** [comment]
Merged into #954
