### ISSUE TITLE
Single-child `WidgetbookComponent`

### ISSUE THREAD

**Issue by YoussefRaafatNasry** [widgetbook/widgetbook#973]
In most cases, users will have a `WidgetbookComponent` with a single use-case as follows:

```dart
WidgetbookComponent(
  name: 'PrimaryButton',
  useCases: [
    WidgetbookUseCase(
      name: 'Default',
      builder: (_) => PrimaryButton(),
    )
  ],
)
```

The above syntax is not only verbose, but it leads to a bad UX for the navigation panel which is full of extra level of nesting. That's why we would like to create a new node type called `WidgetbookLeafComponent` with the following syntax:

```dart
// A component with a single use-case
WidgetbookLeafComponent(
  name: 'PrimaryButton',
  builder: (_) => PrimaryButton(),
)
```

The new node should:
1. Be generated by `widgetbook_generator` for all components with a single use-case.
1. Be rendered as a clickable and non-expandable component in the navigation panel.

**Comment by akarsh-jain-790** [comment]
Hey, @YoussefRaafatNasry I would like to work on this issue, can you assign it to me?

**Comment by YoussefRaafatNasry** [comment]
Hello @akarsh-jain-790 👋 
Any updates here? Otherwise I will have to unassign you so other people can work on this.
