### ISSUE TITLE
"Reset zoom" button should also reset the dragging of the story

### ISSUE THREAD

**Issue by LucasJosefiak** [widgetbook/widgetbook#98]
**Description**
One user suggested that when pressing the "reset zoom" button, the dragging of the usecase should also be resetted.

**Steps To Reproduce**

1. Select an usecase
2. Drag a device
3. Press the "reset zoom" button
4. See that dragging has not been resetted

**Expected Behavior**
"Reset zoom" button should also reset the dragging of the story

**Comment by JensHor** [comment]
I disagree. Zoom and its reset button has nothing to do with with the drag behaviour of the `InteractiveViewer`. Therefore, i am closing this issue and created an issue to track the problem via `InteractiveViewer` in https://github.com/widgetbook/widgetbook/issues/99
