### ISSUE TITLE
Accessibility Addon

### ISSUE THREAD

**Issue by yousinix** [widgetbook/widgetbook#983]
We would like to add an addon based on the [`accessibility_tools`](https://pub.dev/packages/accessibility_tools) package from @rebelappstudio.
The addon should have one `BooleanField` that toggles the package on and off.

**Comment by CoderNamedHendrick** [comment]
Please assign this to me @YoussefRaafatNasry

**Comment by YoussefRaafatNasry** [comment]
Hello @CoderNamedHendrick 👋 

Any updates here?
Otherwise I will have to assign you from this issue so other people can work on it.

**Comment by Tc2r1** [comment]
Please assign this to me.

**Comment by YoussefRaafatNasry** [comment]
Hello @Tc2r1  👋

Any updates here?
Otherwise I will have to unassign you from this issue so other people can work on it.
